### ISSUE TITLE
Requesting For com.valvesoftware.Steam To Default To Mesa-23.2.1

### ISSUE THREAD

**Issue by TeusLollo** [flathub/com.valvesoftware.Steam#1193] opened 2023-11-02 21:21 UTC
We at [Void](https://github.com/void-linux/void-packages) were having the following non-distribution-specific error:

https://github.com/void-linux/void-packages/issues/46649 quote for quote (Check the link for full description):

"
Relevant error log (Flatpak, but its steam-1.0.0.78_3 equivalent is largely identical) is as follows:

`amdgpu_device_initialize: amdgpu_get_auth (1) failed (-1) amdgpu: amdgpu_device_initialize failed. libGL error: glx: failed to create dri3 screen libGL error: failed to load driver: radeonsi Steam Runtime Launch Service: starting steam-runtime-launcher-service Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 336 steam-runtime-launcher-service[336]: E: Unable to acquire bus name "com.steampowered.PressureVessel.LaunchAlongsideSteam" amdgpu_device_initialize: amdgpu_get_auth (1) failed (-1) amdgpu: amdgpu_device_initialize failed. libGL error: glx: failed to create dri3 screen libGL error: failed to load driver: radeonsi
`
"

Which was eventually solved by https://github.com/void-linux/void-packages/issues/46649#issuecomment-1791523149 (Update to `mesa-23.2.1_2`) at least on  `steam-for-linux` native binary, confirming thus that `mesa-23.1.9` indeed throws the aforementioned `auth/libGL` error. 

`com.valvesoftware.Steam` still suffers from the aforementioned error, however, presumably due to defaulting to `mesa-23.1.9`.
Indeed, on my system:

```
flatpak list | grep "Mesa"
Mesa	        org.freedesktop.Platform.GL.default	23.1.9	22.08	        system
Mesa (Extra)	org.freedesktop.Platform.GL.default	23.1.9	22.08-extra	system
Mesa	        org.freedesktop.Platform.GL.default	23.2.1	23.08	        system
Mesa (Extra)	org.freedesktop.Platform.GL.default	23.2.1	23.08-extra	system
Mesa	        org.freedesktop.Platform.GL32.default	23.1.9	22.08	        system
Mesa (Extra)	org.freedesktop.Platform.GL32.default	23.1.9	22.08-extra	system
Mesa	        org.freedesktop.Platform.GL32.default	23.2.1	23.08	        system
Mesa (Extra)	org.freedesktop.Platform.GL32.default	23.2.1	23.08-extra	system
```
I presume thus that `com.valvesoftware.Steam` defaults to `mesa-23.1.9`, hence resulting in the aforementioned error. 

Presumably, defaulting `com.valvesoftware.Steam` to `mesa-23.2.1` would fix this error.

I thus formally request for maintainer(s) to try and verify if defaulting `com.valvesoftware.Steam` to `mesa-23.2.1` would be possible in the near future. 

Thanks to developers for all their efforts, regardless.

**Comment by nanonyme** [comment] 2023-11-07 21:07
Your assumption is incorrect. This app is using runtime version 23.08 and as such Mesa 23.2.1. Apps cannot choose which version of Mesa they use, they get whichever Mesa runtime ships.

**Comment by nanonyme** [comment] 2023-11-07 22:21
I'm not entirely fluent with what is happening here and whether pressure-vessel (subsandboxing) is related or not. It might be useful to have a simpler reproducer (without subsandbox)

**Comment by nanonyme** [comment] 2023-12-15 14:41
I assume everyone here has flatpak 1.12 or newer, right?

**Comment by nanonyme** [comment] 2023-12-22 18:22
If you run the app with `flatpak run --env=LIBGL_DEBUG=verbose com.valvesoftware.Steam`, it might possibly provide more information why exactly the drivers cannot be loaded.

**Comment by nanonyme** [comment] 2023-12-22 22:14
Do you have beta or stable version of the app installed? The error sounds like you are missing i386 compat extensions. You should be getting those automatically when you install stable version of app.

**Comment by nanonyme** [comment] 2023-12-23 19:53
It is truly strange that the allow=multiarch wasn't there to begin with. The app recipe sets it here https://github.com/flathub/com.valvesoftware.Steam/blob/beta/com.valvesoftware.Steam.yml#L38 and it's mandatory.

I have the recollection Mesa in general gives very bad output when device loading fails unless you explicitly request better output through LIBGL_DEBUG=verbose. This gives typically good enough output that you can figure out why loading fails.

I suggest closing the issue yourself, there is no specific not a bug way to close the issue. I have stepped down as maintainer but thought to try to help troubleshoot this one since I was involved earlier.

**Closed as completed** 2023-12-24 02:18 UTC
