### ISSUE TITLE
F12020 doesn't starts

### ISSUE THREAD

**Issue by pablodav** [flathub/com.valvesoftware.Steam#737] opened 2021-04-02 21:39 UTC
**Game information**

I tried the game from steam flatpak and it didn't run, even trying with different proton versions.

After looking into every report here:
https://www.protondb.com/app/1080110

I noticed most of those with issues, are the ones reporting with steam over flatpak.

Then when I tried from native steam in fedora 34 it runs  with no tweaks.

**Distribution name and version where applicable**

Fedora 34

**Flatpak info**

Flatpak 1.10.2
flatpak --gl-drivers
default
host

**Problem description**

**Does this issue reproduce with native Steam**

It works on native steam.

**Comment by nanonyme** [comment] 2021-04-03 06:31
Have you checked if this is duplicate of https://github.com/flathub/com.valvesoftware.Steam/issues/642?

**Comment by pablodav** [comment] 2021-04-03 18:42
Thanks @nanonyme you always help everyone a lot :) 

Yes, looks to be same issue. 
I have installed now the Proton GE 6.5 package from flathub with gnome-software, and the game now runs.

I have updated the text here now:
https://github.com/flathub/com.valvesoftware.Steam/wiki#steam-play-games-do-not-start-for-me

But I think as the current state of proton support, some advertisement with link to this wiki page should be shown to users or some update in the steam description in gnome-software could help users to notice this.

**Comment by nanonyme** [comment] 2021-04-03 19:29
Well, this is why I pinned it at https://github.com/flathub/com.valvesoftware.Steam/issues. Anyway, I'm closing this as duplicate. The issue is that Valve ships new Proton in a way that it's not compatible with flatpak. (it's using pressure vessel)

**Closed by nanonyme** 2021-04-03 19:29 UTC

**Comment by nanonyme** [comment] 2021-04-03 19:31
If you have an idea of how to improve the summary, it's available at https://github.com/flathub/com.valvesoftware.Steam/blob/beta/com.valvesoftware.Steam.metainfo.xml#L14.

**Comment by pablodav** [comment] 2021-04-03 20:14
Thanks a lot!

changes proposed:
https://github.com/flathub/com.valvesoftware.Steam/pull/738
