### ISSUE TITLE
Steam cannot start after update to Nvidia 440.31 (Fedora 31)

### ISSUE THREAD

**Issue by byte1024** [flathub/com.valvesoftware.Steam#512] opened 2019-11-11 19:51 UTC
**Game information**
-

**Distribution name and version where applicable**
Fedora 31 fully updated 11/11/19

**Flatpak info**
 Flatpak 1.4.3
nvidia-440-31
default
host

**Problem description**
Steam flathub version fails to start after update to Nvidia 440.31
Reason: steam killed by SIGSEGV

**Does this issue reproduce with native Steam**
Native Steam cannot work due to missing 32bit from Negativo17

[core_backtrace.txt](https://github.com/flathub/com.valvesoftware.Steam/files/3832990/core_backtrace.txt)

**Comment by byte1024** [comment] 2019-11-11 19:54
[command line.txt](https://github.com/flathub/com.valvesoftware.Steam/files/3832999/command.line.txt)

**Comment by byte1024** [comment] 2019-11-11 19:56
I see swrast is showing up with flathub :-1:

Don't know if that was there before but it shows with 32bit error with native Steam.

**Comment by byte1024** [comment] 2019-11-12 16:13
I see Negativo17 32 bit is available since the last time I looked. Doesn't fix flathub Steam but did fix native Steam...

So now native Steam works and flathub Steam doesn't lol. Feel like I'm playing Whac-A-Mole.

**Comment by nanonyme** [comment] 2019-11-12 21:10
Have you tried running flatpak update after installing the drivers? According to https://github.com/flathub/org.freedesktop.Platform.GL.nvidia your driver should have an extension (I'm suspecting it's not properly installed)

**Comment by nanonyme** [comment] 2019-11-12 21:11
The UX with nVidia proprietary drivers isn't really great. https://github.com/negativo17/nvidia-driver/pull/57 would have made it better but it was never integrated

**Comment by nanonyme** [comment] 2019-11-12 21:14
Note with proprietary drivers you are dependent on Negativo17 or whoever shipping you 32bit driver. If you buy AMD GPU, things will start working more out of the box as the 32bit drivers are shipped as part of org.freedesktop.Platform.

**Comment by monterrr** [comment] 2019-11-17 12:19
Had the same problem, after updating the nvidia drivers from flatpak, problem was solved.

**Comment by monterrr** [comment] 2019-11-17 20:33
This should be closed as it's not a bug.

**Comment by SicLuceatLux** [comment] 2019-11-20 14:30
Well I have the same issue .... but even a complete new setup of flatpak will not solve it. I have deleted the entier instance of flatpak whit any config. A simple flatpak install steam after fresh flatpak setup will not intigirate the nvidia driver as before with nvidia 418. If install the drivers manually the issue is still there. I somehow supect that the branch version might be responsible here? Im new so I dont know if this is true but the nvidiadriver wants to have the org.freedesktop.Platform with branch 1.6 ...using flatpak remove --unused will remove them but next flatpak update will add them again so dead loop

**Comment by nanonyme** [comment] 2019-11-20 15:15
Install --unused is buggy except on quite new flatpak. Run flatpak update after it to pull missing stuff back or get flatpak from PPA.

**Comment by nanonyme** [comment] 2019-11-23 18:19
@SicLuceatLux if flatpak is not installing your extensions, file a bug against flatpak. The repo is here https://github.com/flatpak/flatpak/issues

**Closed by nanonyme** 2019-11-23 18:19 UTC
