### ISSUE TITLE
Unable to launch Worms W.M.D 

### ISSUE THREAD

**Issue by tobias-hammerschmidt** [flathub/com.valvesoftware.Steam#252] opened 2018-10-07 10:48 UTC
**Game information**
Worms W.M.D 

**Distribution name and version where applicable**
Fedora 28

**Flatpak info**
`flatpak --version`
Flatpak 1.0.2

`flatpak --gl-drivers`
default
host

(intel)

**Problem description**
Game does not launch.

```
ERROR: ld.so: object '/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/WormsWMD/Worms W.M.Dx64: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory
```

```
$> ldd Worms\ W.M.Dx64 | grep 'not found'
        libcurl-gnutls.so.4 => not found
        libbz2.so.1.0 => not found
```

**Does this issue reproduce with native Steam**
Have not tested - most likely the game won't work with native steam either since it is only supported on [Ubuntu 14.04 (64-bit version), SteamOS, Linux Mint 17.1](https://steamcommunity.com/app/327030/discussions/2/352792037307797481/?ctp=3#c1697167803858615358). Issue is caused by missing libraries (see https://steamcommunity.com/app/327030/discussions/2/352792037307797481/?ctp=2#c1483233503862669209).

**Comment by erayd** [comment] 2018-10-30 06:11
I'm also seeing the same issue, using flatpak 1.0.4 on Gentoo. System is a late 2013 macbook pro.

Happy to provide additional information, although please note that I am not particularly familiar with flatpak.

**Comment by Shished** [comment] 2018-11-10 16:01
I managed to get it to work.
1. You'll need to copy missing files from the host (they are 64bit)
```
ldd ./Worms\ W.M.Dx64 | grep "not found"
	libcurl-gnutls.so.4 => not found
	libbsd.so.0 => not found
	libidn.so.11 => not found
```
2. Preload libdbus from Steam Runtime (because lib provided by the system is too new?) otherwise game will crash to desktop in main menu
`LD_PRELOAD=~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3 %command%`
and add this LD_PRELOAD to Run.sh.

**Comment by nanonyme** [comment] 2018-11-16 07:44
That 2 is automatically done by Steam. I dunno what's going on

**Comment by nanonyme** [comment] 2018-11-16 07:47
It's very exhausting if libdbus developers actually broke ABI without bumping soname

**Comment by fujexo** [comment] 2018-11-28 12:45
Got the same issue. Is there already a fix?

**Comment by Juhaz** [comment] 2018-12-06 15:12
I hunted down the cause, libdbus developers didn't break the ABI, Debian/Ubuntu had a patch in earlier versions that made fatal warnings behave differently from upstream and they dropped it in dbus 1.12.2.

So - the game is broken, Debian had a patch that hid it from the game developers (fantastic idea there), Debian drops patch, everything goes to hell. And Team 17 undoubtedly doesn't give a shit.

Running it with DBUS_FATAL_WARNINGS=0 makes it run with upstream libdbus (assuming all the other missing libraries have been dealt with)

> dbus (1.12.2-1) unstable; urgency=low
>   * New upstream release 1.12.2
>   * Remove unused Lintian override now that #736360 has been fixed
>   * d/p/debian/Don-t-abort-on-fatal-warnings-by-default.patch:
>     Remove patch. This was committed not long after the addition of the
>     fatal-by-default _dbus_warn_check_failed() checks for programming
>     errors, with the changelog message "This will be set to upstream
>     default again at some point so if you have an application that
>     prints a DBus warning get it fixed".
> 
>     The patch made Debian and its derivatives a little more robust
>     against implementation errors in projects that use libdbus, but at
>     the cost that upstream developers of those projects don't notice
>     implementation errors (that would be crashes on most OSs) if they
>     happen to be developing on Debian or Ubuntu. 11 years later, let's
>     consider "some point" to have arrived.
>   * Set migration urgency to low in case that breaks things.
>  -- Simon McVittie <smcv@debian.org>  Mon, 13 Nov 2017 15:36:08 +0000
>

**Comment by nanonyme** [comment] 2018-12-06 16:31
I wonder how invasive the patch was. If we could get runtime dbus optionally (with environment variable?), that could be turned on in the app. Or maybe we could preload. Good that we now have accurate information though about this

**Comment by Juhaz** [comment] 2018-12-06 17:06
The patch was extremely simple, it just set `static dbus_bool_t fatal_warnings_on_check_failed` to `FALSE` by default instead of `TRUE`

Ie. it had exactly the same effect as having the `DBUS_FATAL_WARNINGS` environment variable as `0`.

**Comment by nanonyme** [comment] 2018-12-06 18:43
Hm, does that mean that if we set DBUS_FATAL_WARNINGS=0 in app manifest, it would probably make the issues go away?

**Comment by Shished** [comment] 2018-12-06 18:54
> Hm, does that mean that if we set DBUS_FATAL_WARNINGS=0 in app manifest, it would probably make the issues go away?
> Can someone please test if "flatpak run --env=DBUS_FATAL_WARNINGS=0 com.valvesoftware.Steam" fixes the issues?

I just tried and game didn't crashed.

**Comment by nanonyme** [comment] 2018-12-07 08:40
Added PR for further discussion. Imo it's not the game makers that are at fault here although . I looked at Dbus API design and this section looked just downright confusing. Why would one even need one function to emit warnings and an identical duplicate of it both of which assert under different configurations of Dbus? Why not just have a function to emit warnings and let people assert when they want to assert? Anyway, with that patch by Debian this was really not an unexpected turn and especially now years after release I'm not sure it's rational to expect fixes.

**Comment by Shished** [comment] 2018-12-07 17:03
What about missing libs? Game still won't work out of box.

**Comment by nanonyme** [comment] 2018-12-07 20:12
The missing libs are a trickier bit since

1. Some of those are unmaintained meaning they might stop working at any time
2. The ones that are maintained might get soname bumps which would result in them basically getting unmaintained for the version you need

**Comment by Juhaz** [comment] 2018-12-07 20:44
All of the "missing" libraries are actually included in the Steam runtime itself. The game is just linked wrong or there's something else weird going on, so in the end it doesn't look for them from there for some reason.

Symlinking `libcurl-gnutls.so.4, libgnutls.so.26, liblber-2.4.so.2, libldap_r-2.4.so.2, librtmp.so.0,libsasl2.so.2, libtasn1.so.3` from `steam-runtime/amd64/usr/lib/x86_64-linux-gnu`
and `libbz2.so.1.0` from `steam-runtime/amd64/lib/x86_64-linux-gnu`

Into `steamapps/common/WormsWMD/lib` in addition to setting DBUS_FATAL_WARNINGS makes it run.

**Comment by nanonyme** [comment] 2018-12-07 20:47
Does the game have a shell wrapper? If so, could someone check what it says? Steam uses LD_LIBRARY_PATH to tell the game where Steam runtime libraries are, some games unset that or set it to something else which breaks everything.

**Comment by Juhaz** [comment] 2018-12-07 21:13
Sorry, I was wrong - symlinking those isn't enough (it makes the game run when launched directly but not through Steam). Looking further into it...

The game has an optional shell wrapper, but it's not the default option (steam prompts on run whether to use the binary straight or "Run.sh"). Neither option works without further tweaking.

The wrapper does override LD_LIBRARY_PATH to "/usr/lib:/usr/local/lib"

**Comment by nanonyme** [comment] 2018-12-07 21:14
Okay, the wrapper most definitely won't work then out of the box

**Comment by nanonyme** [comment] 2018-12-07 21:18
Does the game by chance also set LD_PRELOAD in that wrapper to load some bundled libraries?

**Comment by Juhaz** [comment] 2018-12-10 12:01
No, the wrapper in it's entirety is:

```
#!/bin/bash

export LC_ALL=C
export LD_LIBRARY_PATH="/usr/lib:/usr/local/lib"
chmod a+x ./Worms\ W.M.Dx64
./Worms\ W.M.Dx64
```

**Comment by nanonyme** [comment] 2018-12-10 14:17
Hmm, I truly hope that LC_ALL hack is unnecessary. I already added overrides for some locale variables with negligible user impact but that's very invasive

**Comment by nanonyme** [comment] 2018-12-10 14:19
The executable flag being missing is also quite meh. Could easily prevent running without wrapper

**Comment by nanonyme** [comment] 2018-12-10 19:22
Wrote #276 which should hopefully unbreak all bash-based game wrappers that clear Steam runtime from LD_LIBRARY_PATH.

**Comment by nanonyme** [comment] 2018-12-10 20:06
There's a comment

   flatpak install --user http://repo-test.flathub.org:8080/build-repo/210/com.valvesoftware.Steam.flatpakref

flatpak run com.valvesoftware.Steam # then try game; would be interesting to hear if it affects anything when the game is started through wrapper

**Comment by nanonyme** [comment] 2018-12-10 22:19
Note if installing such snapshots, you'll need to remove and install the Flatpak again to keep getting updates. Games will be preserved.

**Comment by fujexo** [comment] 2018-12-12 12:00
> flatpak install --user http://repo-test.flathub.org:8080/build-repo/218/com.valvesoftware.Steam.flatpakref
> 
> flatpak run com.valvesoftware.Steam # then try game; would be interesting to hear if it affects anything when the game is started through wrapper

Hey, just tried your dev build using both start options but it's not working at least for me.

```
GameAction [AppID 327030, ActionID 3] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 327030, ActionID 3] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 327030, ActionID 3] : LaunchApp continues with user response "0"
GameAction [AppID 327030, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 327030, ActionID 3] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 327030, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 327030, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 327030, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 327030, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 327030 "", ProcID 307, IP 0.0.0.0:0
>>> Adding process 307 for game ID 327030
GameAction [AppID 327030, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/WormsWMD/Worms W.M.Dx64: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory
GameAction [AppID 327030, ActionID 3] : LaunchApp changed task to Completed with ""
>>> Adding process 308 for game ID 327030
Game removed: AppID 327030 "", ProcID 307 
No cached sticky mapping in ActivateActionSet.
```
Using run.sh: 
```
GameAction [AppID 327030, ActionID 4] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 327030, ActionID 4] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 327030, ActionID 4] : LaunchApp continues with user response "1"
GameAction [AppID 327030, ActionID 4] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 327030, ActionID 4] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 327030, ActionID 4] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 327030, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 327030, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 327030, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 327030 "", ProcID 309, IP 0.0.0.0:0
>>> Adding process 309 for game ID 327030
GameAction [AppID 327030, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 327030, ActionID 4] : LaunchApp changed task to Completed with ""
>>> Adding process 310 for game ID 327030
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
./Worms W.M.Dx64: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory
>>> Adding process 311 for game ID 327030
Game removed: AppID 327030 "", ProcID 309 
No cached sticky mapping in ActivateActionSet.
```

Do I have to configure something else?

**Comment by nanonyme** [comment] 2018-12-12 13:42
No, that should have been enough. The traps approach had other issues too but I was expecting it to help here . Ok, we really need to sort this on lower level

**Comment by nanonyme** [comment] 2018-12-27 10:58
I'm first seeing whether upstream (Valve) accepts pulling the package into Steam Runtime.

**Comment by nanonyme** [comment] 2018-12-29 10:41
See discussion in upstream ticket. The version of libbsd0 in Ubuntu 12.04 is very old and odds are it wouldn't work anyway.

**Comment by nanonyme** [comment] 2018-12-29 11:18
@fujexo could you please re-install the regular Flatpak and retry now?

**Comment by fujexo** [comment] 2018-12-29 14:57
> @fujexo could you please re-install the regular Flatpak and retry now?

Just installed the newest version from flathub. Seems like your commit is not yet uploaded there.

Quickly installed the version from your pull request, the game is starting! I only get a yellow pointer and black screen but this could be because of the onboard graphics card.
```
GameAction [AppID 327030, ActionID 2] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 327030, ActionID 2] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 327030, ActionID 2] : LaunchApp continues with user response "0"
GameAction [AppID 327030, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 327030, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 327030, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 327030, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 327030, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 327030, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 327030 "", ProcID 10502, IP 0.0.0.0:0
>>> Adding process 10502 for game ID 327030
GameAction [AppID 327030, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 327030, ActionID 2] : LaunchApp changed task to Completed with ""
>>> Adding process 10503 for game ID 327030
Qt: Session management error: None of the authentication protocols specified are supported
GetCurrentDirectoryA
buffer /home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/WormsWMD
GetCurrentDirectoryA
buffer /home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/WormsWMD
GetCurrentDirectoryA
buffer /home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/WormsWMD
Installing breakpad exception handler for appid(gameoverlayui)/version(20181214221845)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Game update: AppID 327030 "", ProcID 10503, IP 0.0.0.0:0
Setting breakpad minidump AppID = 327030
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198084199855 [API loaded no]
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[1229/155253.162014:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
JS method call Storage.SetString with 2 arguments
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 10541 for game ID 327030
ERROR: ld.so: object '/home/fujexo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 10543 for game ID 327030
pure virtual method called
terminate called without an active exception
Game removed: AppID 327030 "", ProcID 10503 
```

**Comment by Shished** [comment] 2019-01-04 18:08
Steam flatpak got updated and game now works without lib overrides, out of box.

**Comment by nanonyme** [comment] 2019-01-04 18:10
Excellent, closing this.

**Closed by nanonyme** 2019-01-04 18:10 UTC
Labels: game issue

**Comment by Shished** [comment] 2019-01-04 18:15
I haven't tested the 2nd launch option (via Run.sh). It still crashes right after launch.

> ./Worms W.M.Dx64: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

This should be ignored, imo, because it is easier to edit the launch script.

**Comment by nanonyme** [comment] 2019-01-04 18:51
I'd say the launch script is just broken and unsupported.

**Comment by Shished** [comment] 2019-01-08 16:10
Steam overlay is not working after the fix.
Before the fix it worked with this launch option

`LD_PRELOAD=$LD_PRELOAD:~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3 %command%`

**Comment by nanonyme** [comment] 2019-01-08 16:13
I doubt that's related. The only thing that environment variable did was suppress fatal errors. Create separate issue, please.

**Comment by Shished** [comment] 2019-01-08 16:19
I think that's related to missing libs fix.

**Comment by nanonyme** [comment] 2019-01-08 16:22
Why? You mean adding libbsd to app?

**Comment by AsciiWolf** [comment] 2022-10-15 13:44
Game launches and seems to work without a problem now, however the Steam overlay still does not work. Also, there is a weird flickering of the ingame mouse pointer.

**Comment by umop3plsdn** [comment] 2023-04-22 02:35
still broken for me

**Comment by web-on** [comment] 2023-06-27 12:56
For me it best works in compatibility mode with **Proton 3.7**. 
I also added `LC_ALL=C %command%` launch options, but not sure if those are necessary.

At the beginning, when the game launches, there are some team17 and wormsWMD intros, they seem to just be blank screen until you skip them with either Esc key or B key on controller. Once skipped, the rest of the game works fine.

Couldn't make it work with steam runtime. Debian bookworm is the OS - might be the reason.

Proton Experimental works too, and the intros work fine there, but then in some levels the maps of the scenes are not showing - the worms are just hanging in the air. Hopefully that will be fixed in future. Until then using proton 3.7

**Comment by nanonyme** [comment] 2023-06-27 13:47
Please do not comment historic issues. Create new ones.
