### ISSUE TITLE
Fix empty store (requires nss 3.26)

### ISSUE THREAD

**Issue by rshuler** [flathub/com.valvesoftware.Steam#47] opened 2017-12-15 07:50 UTC
I suspect there was a recent update to the external Steam application, and it now has a dependency on nss >= 3.26, but the freedesktop 1.6 runtime has nss 3.25.

This causes the store to be empty:

![screenshot from 2017-12-14 23-15-28](https://user-images.githubusercontent.com/2050162/34032041-1be941ac-e129-11e7-98f5-b33fd045da09.png)

with errors such as the following repeated in the journal every 10 seconds:
```
Dec 14 23:15:20 endless com.valvesoftware.Steam.desktop[1702]: [1214/231520.336090:ERROR:proxy_config_service_linux.cc(274)] Error requesting gconf directory: Failed to activate configuration server: org.freedesktop.DBus.Error.ServiceUnknown
Dec 14 23:15:20 endless com.valvesoftware.Steam.desktop[1702]: [1214/231520.336468:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
Dec 14 23:15:20 endless com.valvesoftware.Steam.desktop[1702]: /sysroot/home/roddy/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_64/steamwebhelper.sh: line 5:   268 Aborted                 (core dumped) ./steamwebhelper "$@"
```

I confirmed that copying libnss3.so from a 3.26 build of nss into /var/lib/flatpak/app/com.valvesoftware.Steam/x86_64/stable/active/files/lib fixed the problem.

**Comment by ernestask** [comment] 2017-12-15 11:16
Dupe of #40.

**Closed** 2017-12-15 14:23 UTC
