### ISSUE TITLE
[Goat Simulator] Black textures

### ISSUE THREAD

**Issue by Exalm** [flathub/com.valvesoftware.Steam#11] opened 2017-06-24 19:22 UTC
As per https://steamcommunity.com/app/265930/discussions/1/540738050968371574
Q: (Linux) The textures are missing, most objects shows up black, how can I fix it?
If the package libtxc-dxtn isn't installed the textures isn't loaded correctly and most objects becomes black. You can fix this by installing the missing package. If you're using Ubuntu, Linux Mint or any other Ubuntu based linux distribution you can install the package by typing this into the terminal:
sudo apt-get install libtxc-dxtn-s2tc0 libtxc-dxtn-s2tc0:i386 

I have the same issue on Fedora 26 and Intel GPU, and the package is called just libtxc_dxtn here. Installing it in the host system doesn't work with flatpak-ed Steam, but bundling with flatpak will probably do the thing.

**Comment by Exalm** [comment] 2017-06-24 19:59
Also, it seems that Endless's Steam flatpak does that:
https://github.com/endlessm/steam-flatpak/blob/master/com.valvesoftware.Steam.json
There is a mention of that library.

**Comment by TingPing** [comment] 2017-06-24 20:40
Duplicate of #2

**Closed by TingPing** 2017-06-24 20:40 UTC
