### ISSUE TITLE
Complains about overrides it has no business caring about

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/com.valvesoftware.Steam#700] opened 2021-01-12 14:55 UTC
Hi there. I installed the Flatpak version of Steam so I could test out the fix on #608 for you all but upon trying to start it, found it was complaining about some of the global overrides I have.

```
Aura ~ $ dgpu flatpak run com.valvesoftware.Steam
https://github.com/flathub/com.valvesoftware.Steam/wiki
Bad item "xdg-config/gtk-3.0:ro" found in filesystem overrides
Bad item "xdg-data/icons:ro" found in filesystem overrides
Bad item "xdg-config/dconf:ro" found in filesystem overrides
Bad item "xdg-config/MangoHud:ro" found in filesystem overrides
Please see https://github.com/flathub/com.valvesoftware.Steam/wiki#i-want-to-add-external-disk-for-steam-libraries
```

When I tried to reverse the overrides specifically for Steam using `flatpak override --nofilesystem=...`, it resulted in this when I tried to start it:

```
Aura ~ $ dgpu flatpak run com.valvesoftware.Steam
bwrap: Can't make symlink at /home/tiz/xdg/share/icons: File exists
```

What sort of shenanigans is the package trying to pull? I understand it's taking special care to protect home, but why does it care about read-only overrides of specific subdirectories of XDG dirs? I'm not going to remove them from my global overrides, they all serve specific purposes.

* **xdg-config/gtk-3.0:** Allows my gtk.css to be picked up by Flatpak apps.
* **xdg-data/icons:** Makes my installed cursor themes usable by Flatpak apps.
* **xdg-config/dconf:** This one I can probably drop because it's not working anyways; it's for GTK file picker settings.
* **xdg-config/MangoHud:** I have MangoHud installed such that all Flatpak apps--like RPCS3 or Dolphin--can use it, and thus need my config file.

Can we scale back the protections a bit?

**Comment by gasinvein** [comment] 2021-01-12 16:11
This was introduced in #672 to prevent dangerous issues like #667, and was dropped again in current beta after #698. In short, this is needed to prevent the steam wrapper from messing with your files passed through from host (and the wrapper is needed to make Steam Cloud sync work for all games).
We're considering how to handle it better while not prohibiting such overrides completely. Sorry for the confusion.
For now, you can try the beta branch of this app (you'll also need to install beta branches of Proton/MangoHud/etc extensions to use them).

**Comment by HugLifeTiZ** [comment] 2021-01-21 20:18
The beta branch is still trying to pull symlink overwriting shenanigans, unfortunately. :/

**Comment by nanonyme** [comment] 2021-01-21 22:32
What do you mean by symlink overriding shenanigans?

**Comment by HugLifeTiZ** [comment] 2021-01-22 14:56
```
Aura ~ $ flatpak run com.valvesoftware.Steam
bwrap: Can't make symlink at /home/tiz/.icons: File exists
Aura ~ $ sudo nano /var/lib/flatpak/overrides/global
[sudo] password for tiz: 
Aura ~ $ # Removed ~/.icons:ro from overrides
Aura ~ $ flatpak run com.valvesoftware.Steam
bwrap: Can't make symlink at /home/tiz/xdg/share/icons: File exists
```

It seems like it's trying to make symlinks on top of my overrrides.

**Comment by gasinvein** [comment] 2021-01-22 15:39
Error message from bwrap indicate that the app execution didn't even reach our wrapper, so this could be a different issue.

Can you please rename the `~/.var/app/com.valvesoftware.Steam` directory and then try launching Steam flatpak beta?

**Comment by HugLifeTiZ** [comment] 2021-01-22 16:13
```
Aura ~ $ rm -r .var/app/com.valvesoftware.Steam/
Aura ~ $ flatpak run com.valvesoftware.Steam
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:migration:Copying /home/tiz/.var/app/com.valvesoftware.Steam/config to /home/tiz/.var/app/com.valvesoftware.Steam/.config, ignoring {'gtk-3.0', 'MangoHud'}
INFO:migration:Renaming /home/tiz/.var/app/com.valvesoftware.Steam/config to /home/tiz/.var/app/com.valvesoftware.Steam/config.old
INFO:migration:Symlinking /home/tiz/.var/app/com.valvesoftware.Steam/config to .config
INFO:migration:Copying /home/tiz/.var/app/com.valvesoftware.Steam/data to /home/tiz/.var/app/com.valvesoftware.Steam/.local/share, ignoring {'Steam', 'icons'}
INFO:migration:Renaming /home/tiz/.var/app/com.valvesoftware.Steam/data to /home/tiz/.var/app/com.valvesoftware.Steam/data.old
INFO:migration:Symlinking /home/tiz/.var/app/com.valvesoftware.Steam/data to .local/share
INFO:migration:Copying /home/tiz/.var/app/com.valvesoftware.Steam/cache to /home/tiz/.var/app/com.valvesoftware.Steam/.cache, ignoring set()
INFO:migration:Deleting /home/tiz/.var/app/com.valvesoftware.Steam/cache
INFO:migration:Symlinking /home/tiz/.var/app/com.valvesoftware.Steam/cache to .cache
INFO:root:Restarting app due to finalize sandbox tuning
bwrap: Can't make symlink at /home/tiz/xdg/share/icons: File exists
```

**Comment by gasinvein** [comment] 2021-01-22 16:26
Ok, this looks like a different issue indeed: the wrapper completed migration successfuly and didn't complain about improper overrides, but on the next launch bwrap couldn't set up the sandbox.

The `/home/tiz/xdg/share/icons` directory seems pretty unusual. I guess `XDG_DATA_HOME` on your host points to `/home/tiz/xdg/share`? Are there any symlinks, is it a symlink itself?

**Comment by HugLifeTiZ** [comment] 2021-01-22 17:10
On my system, `XDG_CONFIG_HOME=$HOME/xdg/config` and `XDG_DATA_HOME=$HOME/xdg/share`. `~/xdg` replaces `~/.local`, but there is a symlink maintained for compatibility. Similarly `~/.config` is just a symlink to `~/xdg/config`.

It looks like I have `~/xdg/share/icons` as a symlink to `/xusr/share/icons`. I also have `~/xdg/share/themes` as a similar symlink. I have `/xusr/share:ro` as a global override, and `/xusr/share` is in `XDG_DATA_DIRS` also exposed as a global override. If I made symlinks into `/xusr/share`, it means that something wasn't reading `XDG_DATA_DIRS` like it's supposed to. But I can't remember what the heck I did that for.

In any case, looks like my custom setup broke stuff. I should take some time to document it and get into the habit of documenting what prompts me to do workarounds. For all I know they may not be necessary anymore.

**Comment by gasinvein** [comment] 2021-01-22 17:26
>I have `~/xdg/share/icons` as a symlink to `/xusr/share/icons`.

Now this feels similar to flatpak/flatpak#1971: as I understand it, flatpak gets confused when you pass through a directory from host which is a symlink, together with the app having `--presist=.`

> For all I know they may not be necessary anymore.

What if you launch Steam via `env XDG_DATA_HOME=/xusr/share flatpak ...`, will it work then?

**Comment by nanonyme** [comment] 2021-01-22 20:34
Okay. I think that area goes quite deep into area we haven't been testing thoroughly. The cases where xdg paths pointed to their default locations definitely were tested and they worked fine with overrides.

**Comment by gasinvein** [comment] 2021-01-22 21:07
I think that non-default path should be fine, it's symlinks what triggers the issue. It can be reproduced like this:
```bash
mkdir -p ~/some-dir
ln -s some-dir ~/some-dir-symlink
flatpak run --command=true --filesystem=~/some-dir:ro --filesystem=~/some-dir-symlink:ro com.valvesoftware.Steam
# first run is fine
flatpak run --command=true --filesystem=~/some-dir:ro --filesystem=~/some-dir-symlink:ro com.valvesoftware.Steam
# subsequent runs throw error: bwrap: Can't make symlink at /home/gasinvein/some-dir-symlink: File exists
```

**Comment by HugLifeTiZ** [comment] 2021-01-22 22:55
> For all I know they may not be necessary anymore.

I was right. If an app uses GTK (and probably also Qt but I didn't check), it knows to look for cursors in the icons subdirs for each dir in `XDG_DATA_DIRS`. However, if an app does *not* use GTK--looking at you, bevy of Electron apps packaged in Flathub--you define its search locations with `XCURSOR_PATH` instead. (Found that out [here.](https://www.x.org/releases/current/doc/man/man3/Xcursor.3.xhtml)) After setting that variable and exposing it with overrides, I no longer need neither `~/.icons` nor `xdg-data/icons`, both in terms of their symlinks or overrides.

After another `rm -r .var/app/com.valvesoftware.Steam`, I am able to start the beta version of Steam successfully.

**Comment by gasinvein** [comment] 2021-01-23 09:45
Well, I believe the original issue is fixed in beta? I.e. the wrapper ignored your overrides instead of complaining about them.

**Comment by nanonyme** [comment] 2021-01-23 09:54
Created https://github.com/flathub/com.valvesoftware.Steam/pull/707

**Comment by HugLifeTiZ** [comment] 2021-01-23 17:10
Yes, the original issue is fixed. :)

**Comment by nanonyme** [comment] 2021-01-23 18:18
I think there's existing bugs about the remaining so let's close this one.

**Closed by nanonyme** 2021-01-23 18:18 UTC

**Comment by All3xJ** [comment] 2023-02-13 23:32
I have the same bug (got it when I enabled the home folder sharing). I eventually uninstalled the steam flatpak version and installed the repo version.

**Comment by HugLifeTiZ** [comment] 2023-02-24 00:18
> I have the same bug (got it when I enabled the home folder sharing).

That's not a bug. You're not supposed to override to enable access to your entire home folder, only specific folders. This is because Steam is proprietary and all of the apps you use it to download are proprietary too; they should be treated as untrusted, and you should only allow them access to exactly the directories you need them to have.

**Comment by nanonyme** [comment] 2023-02-24 08:07
It's not actually because of that. It's because flatpak app has to do magic to make Steam Cloud sync work. It will break your user home if you expose your real home to the app.
