### ISSUE TITLE
Transparent tray icon.

### ISSUE THREAD

**Issue by ghost** [flathub/com.valvesoftware.Steam#382] opened 2019-06-30 02:59 UTC
I installed Ubuntu 19.10 today and I thought I would give the Flatpak version of Steam a try, I managed to figure out how to use my second drive however I have just noticed the tray icon doesn't have an icon. Steam is in the tray and I can click on it to get options however the icon is missing so it looks as though it is not there.

**Comment by nanonyme** [comment] 2019-06-30 06:29
Probably duplicate of https://github.com/flathub/com.valvesoftware.Steam/issues/322

**Comment by nanonyme** [comment] 2021-03-23 20:31
Closed since the linked item is now closed as well.

**Closed by nanonyme** 2021-03-23 20:31 UTC
