### ISSUE TITLE
Chat does not work

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#120] opened 2018-08-01 20:36 UTC
FRIENDS NETWORK UNREACHABLE
This failure may indicate that your local network is offline or that the Steam Friends servers are currently offline.
![captura de tela de 2018-08-01 17-34-07](https://user-images.githubusercontent.com/26097419/43547295-3950f3ba-95b1-11e8-8b86-80903c965a08.png)

**Comment by pschichtel** [comment] 2018-08-03 17:37
Have you checked if some firewall block{s,ed} it or if the servers were indeed offline? Never had that issue.

**Comment by LeandroStanger** [comment] 2018-08-03 20:34
This problem happens all the time


```
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
sh: lspci: command not found
Installing breakpad exception handler for appid(steam)/version(1533163808)
surface_linux.cpp (2095) : Assertion Failed: None of the authentication protocols specified are supported
Assert( Assertion Failed: None of the authentication protocols specified are supported ):surface_linux.cpp:2095

Installing breakpad exception handler for appid(steam)/version(1533163808)
crash_20180803173100_5.dmp[144]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180803173100_5.dmp
[0803/173102.754128:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0803/173102.754365:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1533162461
[0803/173102.754385:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0803/173102.754402:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 20180801222741
[0803/173102.754421:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0803/173102.754438:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
crash_20180803173100_5.dmp[144]: Finished uploading minidump (out-of-process): success = yes
crash_20180803173100_5.dmp[144]: response: CrashID=bp-42562494-19d3-4b5a-bd17-ecdf32180803
crash_20180803173100_5.dmp[144]: file ''/tmp/dumps/crash_20180803173100_5.dmp'', upload yes: ''CrashID=bp-42562494-19d3-4b5a-bd17-ecdf32180803''
[0803/173104.210396:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
CAppInfoCacheReadFromDiskThread took 306 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
[0803/173107.209839:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0803/173107.209939:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1533163808
[0803/173107.210009:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0803/173107.210070:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 20180801222741
[0803/173107.210130:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0803/173107.210193:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
CApplicationManagerPopulateThread took 3232 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)

** (steam:134): WARNING **: Unknown device type 14

** (steam:134): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198150436929 [API loaded no]
Installing breakpad exception handler for appid(steam)/version(1533163808)
[0803/173109.587819:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
[0803/173109.614427:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization

** (steam:134): WARNING **: Unknown setting 'proxy'

** (steam:134): WARNING **: Unknown setting 'user'

** (steam:134): WARNING **: Ignoring invalid property 'route-data'

** (steam:134): WARNING **: Ignoring invalid property 'address-data'

** (steam:134): WARNING **: Ignoring invalid property 'route-data'

** (steam:134): WARNING **: Ignoring invalid property 'address-data'

** (steam:134): WARNING **: Ignoring invalid property 'autoconnect-priority'

** (steam:134): WARNING **: Unknown setting 'proxy'

** (steam:134): WARNING **: Ignoring invalid property 'route-data'

** (steam:134): WARNING **: Ignoring invalid property 'address-data'

** (steam:134): WARNING **: Ignoring invalid property 'route-data'

** (steam:134): WARNING **: Ignoring invalid property 'address-data'

** (steam:134): WARNING **: Unknown setting 'proxy'

** (steam:134): WARNING **: Unknown setting 'user'

** (steam:134): WARNING **: Ignoring invalid property 'route-data'

** (steam:134): WARNING **: Ignoring invalid property 'address-data'

** (steam:134): WARNING **: Ignoring invalid property 'route-data'

** (steam:134): WARNING **: Ignoring invalid property 'address-data'

** (steam:134): WARNING **: Ignoring invalid property 'autoconnect-priority'

** (steam:134): WARNING **: Unknown setting 'proxy'

** (steam:134): WARNING **: Ignoring invalid property 'route-data'

** (steam:134): WARNING **: Ignoring invalid property 'address-data'

** (steam:134): WARNING **: Ignoring invalid property 'route-data'

** (steam:134): WARNING **: Ignoring invalid property 'address-data'
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1533163808)
Found unsupported CDM version 1.4.9.1088, using last known good version 1.4.8.1008

(steam:134): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)
roaming config store loaded successfully - 2436 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1533163808)
Installing breakpad exception handler for appid(steam)/version(1533163808)

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:134): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
[0803/173117.669914:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0803/173117.670145:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1533162461
[0803/173117.670164:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0803/173117.670182:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 20180801222741
[0803/173117.670200:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0803/173117.670218:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
Failed to init SteamVR because it isn't installed
sh: lspci: command not found
ExecCommandLine: "'/sysroot/home/leandro/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam' '--debug'"
System startup time: 24,07 seconds
Generating new string page texture 77: 64x256, total string texture memory is 65,54 KB
Generating new string page texture 78: 64x256, total string texture memory is 376,83 KB
Generating new string page texture 79: 128x256, total string texture memory is 507,90 KB
/usr/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS64
Failed to load module: /usr/lib/gio/modules/libdconfsettings.so
/usr/lib/gio/modules/libgiognutls.so: wrong ELF class: ELFCLASS64
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
/usr/lib/gio/modules/libgiolibproxy.so: wrong ELF class: ELFCLASS64
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognomeproxy.so: wrong ELF class: ELFCLASS64
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
JS method call WebChat.GetWebChatLanguage with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetSignIntoFriendsOnStart with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
JS method call WebChat.GetLocalPersonaName with 1 arguments
JS method call WebChat.GetLocalAvatarBase64 with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
JS method call WebChat.GetLocalPersonaName with 1 arguments
JS method call WebChat.GetLocalAvatarBase64 with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
JS method call WebChat.GetLocalPersonaName with 1 arguments
JS method call WebChat.GetLocalAvatarBase64 with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
JS method call WebChat.GetLocalPersonaName with 1 arguments
JS method call WebChat.GetLocalAvatarBase64 with 1 arguments
Exiting workitem thread
[2018-08-03 17:30:54] Startup - updater built Aug  1 2018 22:26:43
[2018-08-03 17:30:55] Verificando a instalação...
[2018-08-03 17:30:55] Verification complete
[2018-08-03 17:32:45] Shutdown

```

**Comment by LeandroStanger** [comment] 2018-08-09 10:54
@nedrichards Could help? Topic:[ https://community.endlessos.com/t/tip-using-steam-on-endless-os/2080/38]( https://community.endlessos.com/t/tip-using-steam-on-endless-os/2080/38?u=leandrostanger)

**Comment by EspadaV8** [comment] 2018-08-09 10:56
I've had this issue since the new chat came out too, running Fedora 28, flatpak and system fully updated.

**Comment by nanonyme** [comment] 2018-08-09 11:16
Are you @EspadaV8 also with non-English locale? I haven't been able to reproduce this so there might be something common with failing user machines. At this point I suspect locales may play a part at this

**Comment by EspadaV8** [comment] 2018-08-09 20:32
I should be configured with an English locale, `en_GB.UTF8`, but I will double check when I'm next at the computer

**Comment by nanonyme** [comment] 2018-08-09 22:00
It might be enough that locale differs from en_US if I understood correctly the issues Steam was having because of locale related to CS:GO. Those should be fixed upstream but there's also reports Steam isn't updating so I dunno

**Comment by EspadaV8** [comment] 2018-08-10 11:27
Configured my system locale, rebooted and re-launched Steam and get the same issue

```
espadav8@localhost:~
> localectl set-locale LANG=en_US.utf8

// ... reboot ...

espadav8@localhost:~
> localectl status                   
   System Locale: LANG=en_US.utf8
       VC Keymap: us
      X11 Layout: us

espadav8@localhost:~
> flatpak run com.valvesoftware.Steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
sh: lspci: command not found
Installing breakpad exception handler for appid(steam)/version(1533766730)
[0810/212457.745838:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0810/212457.745898:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1533764000
[0810/212457.745903:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0810/212457.745908:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 20180808213320
[0810/212457.745912:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0810/212457.745916:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
[0810/212457.800919:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
[0810/212457.857680:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0810/212457.857716:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1533766730
[0810/212457.857733:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0810/212457.857747:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 20180808213320
[0810/212457.857754:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0810/212457.857760:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
CApplicationManagerPopulateThread took 9 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)
CAppInfoCacheReadFromDiskThread took 103 milliseconds to initialize

** (steam:130): WARNING **: Unknown device type 13

** (steam:130): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/5: unknown object type

** (steam:130): WARNING **: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:130): WARNING **: Unknown device type 13

** (steam:130): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type

** (steam:130): WARNING **: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:130): WARNING **: Unknown device type 13

** (steam:130): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:130): WARNING **: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:130): WARNING **: Unknown device type 14

** (steam:130): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type

** (steam:130): WARNING **: Unknown device type 13

** (steam:130): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:130): WARNING **: Unknown device type 13

** (steam:130): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type

** (steam:130): WARNING **: Unknown device type 13

** (steam:130): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/5: unknown object type

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Unknown setting 'proxy'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Ignoring invalid property 'autoconnect-priority'

** (steam:130): WARNING **: Unknown setting 'proxy'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Ignoring invalid property 'interface-name'

** (steam:130): WARNING **: Unknown setting 'proxy'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Unknown setting 'bridge'

** (steam:130): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/3 settings: (3) type

** (steam:130): WARNING **: Ignoring invalid property 'interface-name'

** (steam:130): WARNING **: Unknown setting 'proxy'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Unknown setting 'bridge'

** (steam:130): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/5 settings: (3) type

** (steam:130): WARNING **: Ignoring invalid property 'interface-name'

** (steam:130): WARNING **: Unknown setting 'proxy'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Ignoring invalid property 'route-data'

** (steam:130): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:130): WARNING **: Ignoring invalid property 'address-data'

** (steam:130): WARNING **: Unknown setting 'bridge'

** (steam:130): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/4 settings: (3) type
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1533766730)
Installing breakpad exception handler for appid(steam)/version(1533766730)

(steam:130): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1533766730)
WARNING: radv is not a conformant vulkan implementation, testing use only.
[0810/212459.859434:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Installing breakpad exception handler for appid(steam)/version(1533766730)
[0810/212500.860872:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
roaming config store loaded successfully - 9151 bytes.
migrating temporary roaming config store
[0810/212501.723905:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0810/212501.723965:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1533764000
[0810/212501.723972:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0810/212501.723977:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 20180808213320
[0810/212501.723982:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0810/212501.723987:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
Failed to init SteamVR because it isn't installed
sh: lspci: command not found
ExecCommandLine: "'/home/espadav8/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam'"
System startup time: 5.11 seconds
[0810/212502.366702:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Generating new string page texture 78: 1024x256, total string texture memory is 1.36 MB
Generating new string page texture 79: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 80: 128x256, total string texture memory is 1.49 MB
Generating new string page texture 81: 64x256, total string texture memory is 1.56 MB
Generating new string page texture 82: 32x256, total string texture memory is 1.59 MB
Generating new string page texture 87: 128x256, total string texture memory is 1.72 MB
Generating new string page texture 88: 128x256, total string texture memory is 1.85 MB
Generating new string page texture 89: 256x256, total string texture memory is 2.11 MB
Generating new string page texture 91: 64x256, total string texture memory is 2.18 MB
Generating new string page texture 92: 128x256, total string texture memory is 2.31 MB
CAPIJobRequestUserStats - Server response failed 2
JS method call WebChat.GetWebChatLanguage with 1 arguments
Generating new string page texture 98: 384x256, total string texture memory is 2.70 MB
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetSignIntoFriendsOnStart with 1 arguments
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197994148763 [API loaded no]
[0810/212502.939572:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
Generating new string page texture 102: 256x256, total string texture memory is 2.97 MB
[0810/212503.367549:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Found unsupported CDM version 1.4.9.1088, using last known good version 1.4.8.1008
Installing breakpad exception handler for appid(steam)/version(1533766730)

**Comment by nanonyme** [comment] 2018-08-14 17:56
Does this still reproduce with the latest Steam? Asking since runtime was just significantly updated

**Comment by SuperKingZ** [comment] 2018-08-15 17:57
I also been having this same problem after the new steam update.  The problem seems to be something to do with timezones. If I start the flatpak with "flatpak run --command=bash com.valvesoftware.Steam" and run "export TZ=America/New_York" the chat works as expected but if I run "flatpak run com.valvesoftware.Steam" the chat is not working.

**Comment by SuperKingZ** [comment] 2018-08-15 18:32
I fix the probem by adding "export TZ=America/New_York" to the end of the "/etc/profile" file

**Comment by nanonyme** [comment] 2018-08-15 18:50
Do you mean in the host or the guest?

**Comment by SuperKingZ** [comment] 2018-08-15 19:11
I change the file on the host. Before the edit the TZ value was blank on guest and host

**Comment by nanonyme** [comment] 2018-08-15 19:19
I'm a bit sceptical because I don't have TZ set and it works for me

**Comment by SuperKingZ** [comment] 2018-08-15 19:37
I made a video showing the problem in action. I will remove the video in a week https://www.youtube.com/watch?v=e-7O9Nossx4

**Comment by nanonyme** [comment] 2018-08-15 19:54
That's so bizarre. Could it be that there would be a difference with it not being set at all and it being set to a blank value?

**Comment by SuperKingZ** [comment] 2018-08-15 20:01
I found the problem! I remove the host "/etc/profile" TZ export and change host "/etc/localtime" from "ln -sf "/usr/share/zoneinfo/Africa/Johannesburg /etc/localtime" to "ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime" and now my chat works with an empty TZ value.

**Comment by nanonyme** [comment] 2018-08-15 20:08
Still confused why that would affect anything. If you set localtime to original and open container through flatpak run --command=bash com.valvesoftware.Steam, what does ls -l /etc/localtime say? Does it point to something existing or is it a broken symlink?

**Comment by SuperKingZ** [comment] 2018-08-15 20:12
In guest
lrwxrwxrwx 1 sirolf users 27 Aug 15 16:09 /etc/localtime -> /run/host/monitor/localtime
-rw-r--r-- 1 sirolf users 3545 Aug 15 15:54 /run/host/monitor/localtime

**Comment by nanonyme** [comment] 2018-08-16 07:39
Can you please set TZ to your actual time zone (Johannesburg as it was) while system runs in that timezone as well? Looks like setting TZ may be making Steam skip reading /etc/localtime allowing the workaround in the other ticket to work. If thus helps, we might be able to port it into the Flatpak application

**Comment by SuperKingZ** [comment] 2018-08-16 09:49
Steam works if I set TZ to my current zone. As long as TZ is valid and not null steam chat works as expected

**Comment by nanonyme** [comment] 2018-08-16 10:27
As said, I think the null TZ makes Steam read localtime which apparently is not reliable

**Comment by nanonyme** [comment] 2018-08-16 10:29
@LeandroStanger can you please test if setting TZ remediates the situation for you?

**Comment by LeandroStanger** [comment] 2018-08-16 11:18
@nanonyme Corrected
![captura de tela de 2018-08-16 08-15-25](https://user-images.githubusercontent.com/26097419/44205458-d80a8080-a12c-11e8-9e69-398f1607499a.png)

**Comment by nanonyme** [comment] 2018-08-16 22:35
Incidentally the workaround will not work as is. After I have refactored steam-wrapper into Python as part of future-proofing (PR will fix #60 ), planning to use https://python-datetime-tz.readthedocs.io/en/latest/#datetime_tz.detect_timezone to set TZ. That seems promising at that point. Please set TZ yourself in the meantime like so

flatpak override --env=TZ=... com.valvesoftware.Steam

**Comment by EspadaV8** [comment] 2018-08-18 02:31
`flatpak override --user --env=TZ=Australia/Brisbane com.valvesoftware.Steam` worked for me and chat now loads correctly when running steam as normal. Thanks @nanonyme and @SuperKingZ for the digging and fixing

**Comment by nanonyme** [comment] 2018-08-18 19:25
Well, not really fixed yet. You should be able to use the app without overrides for regular usecases

**Comment by nanonyme** [comment] 2018-08-19 20:29
There's now a best-effort timezone guessing workaround integrated. Please remove TZ override, update and re-test

**Comment by tomgar** [comment] 2018-09-08 09:06
The workaround would be better if it interprets a TZ env which references a file. In my case I have set TZ as :/etc/localtime for good reasons: 
https://blog.packagecloud.io/eng/2017/02/21/set-environment-variable-save-thousands-of-system-calls/ 
, being this way of setting up the TZ env part of the spec:
https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html (search for third format)

In your steam-wrapper, you are almost there... you need to check if the TZ env starts with a colon and then check if it's a symbolic link and follow it. Either after that or if it's not a symbolic link, just extract the filename as you are already doing in that for loop.

Steam doesn't work with this kind of TZ representation so that's why I'm commenting here:
https://github.com/ValveSoftware/steam-for-linux/issues/5609

Hopefully Steam will fix this issue in their side some day...

**Comment by nanonyme** [comment] 2018-09-08 10:41
That doesn't actually work with Flatpak. The symlink points to a file under /run

**Comment by nanonyme** [comment] 2018-09-08 10:43
Oh, you meant resolving indirect TZ

**Comment by nanonyme** [comment] 2018-09-08 10:59
Note that it's not enough to follow. We're talking about a sandbox so if user sets TZ, so user setting third format will likely not point nowhere at all.

**Comment by Israphel** [comment] 2019-02-12 18:06
is this supposed to be working nowadays? My chat doesn't work

**Comment by nanonyme** [comment] 2019-02-12 19:29
It should, yes.

**Comment by Israphel** [comment] 2019-02-12 20:21
yes, FRIENDS NETWORK UNREACHABLE

**Comment by Israphel** [comment] 2019-02-14 22:49
Full log here: https://gist.github.com/Israphel/aa5af1a358e4228667100db3c99b3fd9

**Comment by fabriciojardim** [comment] 2019-02-16 13:06
Apparently, I got the same issue.
Flatpak 1.2.3
Ubuntu 18.04.2

Command flatpak override --user --env=TZ=America/Sao_Paulo com.valvesoftware.Steam fixed the issue.

[steam-flatpak-output.txt](https://github.com/flathub/com.valvesoftware.Steam/files/2871933/steam-flatpak-output.txt)

**Comment by nanonyme** [comment] 2019-02-16 14:40
Well, it's not printing something like "Overriding TZ to {zone_name}" in above log so sounds like the timezone workaround isn't working correctly.

**Comment by nanonyme** [comment] 2019-02-16 14:41
See https://github.com/flathub/com.valvesoftware.Steam/blob/master/steam_wrapper/steam_wrapper.py#L56

**Comment by nanonyme** [comment] 2019-02-16 21:18
There's now a differently working workaround which should be more robust but requires Flatpak 1.1.0 to work at all. Does it work any better now?

**Comment by LeandroStanger** [comment] 2019-02-16 22:34
@nanonyme The bug is still happening

**Comment by nanonyme** [comment] 2019-02-16 22:35
Can you now see anything in your console log about timestamp?

**Comment by LeandroStanger** [comment] 2019-02-16 22:59
@nanonyme No

**Comment by LeandroStanger** [comment] 2019-03-20 22:02
This has been fixed with the latest Steam Beta update

**Comment by LeandroStanger** [comment] 2019-03-20 22:03
@nanonyme This has been fixed with the latest Steam Beta update

**Closed** 2019-03-20 22:03 UTC
Labels: game issue
