### ISSUE TITLE
Big Picture mode display issues

### ISSUE THREAD

**Issue by Wetrain** [flathub/com.valvesoftware.Steam#133] opened 2018-08-16 16:21 UTC
Hi,

I was testing steam now it is running on top of 18.08.

I launched big picture mode to see if it would work and noticed i do not get any audio, so I tabbed out of the big picture mode to see my audio settings in Pulse, once I tabbed back to the big picture mode, the app began to have lots of fragmentation issues, which look like the photo attached.

![screenshot from 2018-08-16 17-17-28](https://user-images.githubusercontent.com/4598620/44221251-bd5df900-a178-11e8-9263-22530a721ea3.png)

**Comment by Wetrain** [comment] 2018-08-16 16:27
I am using Wayland, but have no tested with native steam, i will try and let you know!

**Comment by nanonyme** [comment] 2018-08-16 16:35
If it reproduces there, could be something to do with XWayland

**Comment by Wetrain** [comment] 2018-08-16 16:54
@nanonyme seems installing steam native on Arch is not easy, so not sure i will be able to reproduce, i'm missing a lot of 32bit libs

**Comment by nanonyme** [comment] 2018-09-11 20:03
Does this still reproduce? I couldn't reproduce the graphics corruption when I just tried. Iirc I got it before.

**Comment by nanonyme** [comment] 2019-06-25 07:34
Closing, no feedback.

**Closed by nanonyme** 2019-06-25 07:34 UTC
Labels: bug
