### ISSUE TITLE
Steam crashing 

### ISSUE THREAD

**Issue by Zympp1** [flathub/com.valvesoftware.Steam#551] opened 2020-04-08 06:17 UTC
My drivers are 440.82. I have nVidia
The error when I try to open through terminal is:

Installing breakpad exception handler for appid(steam)/version(1586022601)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1586022601)
Installing breakpad exception handler for appid(steam)/version(1586022601)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  48
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  47
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  49
xerror_handler: X failed, continuing
crash_20200408091702_1.dmp[167]: Uploading dump (out-of-process)
/tmp/dumps/crash_20200408091702_1.dmp
/home/jl/.local/share/Steam/steam.sh: rivi 722:  145 Muistialueen ylitys     (luotiin core-tiedosto)$STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20200408091702_1.dmp[167]: Finished uploading minidump (out-of-process): success = yes
crash_20200408091702_1.dmp[167]: response: CrashID=bp-a9def603-d3d7-4a6e-aa34-58b612200407
crash_20200408091702_1.dmp[167]: file ''/tmp/dumps/crash_20200408091702_1.dmp'', upload yes: ''CrashID=bp-a9def603-d3d7-4a6e-aa34-58b612200407''

**Comment by nanonyme** [comment] 2020-04-08 06:53
Do you have nVidia?

**Comment by Zympp1** [comment] 2020-04-08 06:59
Yes!

**Comment by nanonyme** [comment] 2020-04-08 07:06
Please always start bug reports with that and your driver version. There's a tempate for a reason.

**Comment by Zympp1** [comment] 2020-04-08 07:07
How do I a know what drivers i have?

**Comment by Zympp1** [comment] 2020-04-08 07:09
Oh i found i think my drivers are 440.82

**Comment by nanonyme** [comment] 2020-04-08 07:12
Ping @TingPing is this the driver version that was discussed yesterday as missing?

**Comment by andejong** [comment] 2020-04-08 10:14
I have the same issue.

**Comment by dgmulf** [comment] 2020-04-08 23:54
I had the same issue last night. Today, flatpak had updates for nvidia-related packages, which fixed the issue. I'm on Arch, and I wonder if this is caused by nvidia driver updates rolling out sooner on the Arch Linux official repos than flathub?

**Comment by nanonyme** [comment] 2020-04-09 12:37
Yes, you need to reboot and run flatpak update after updating nvidia drivers to ensure a consistently working system

**Comment by dgmulf** [comment] 2020-04-09 20:56
That's unacceptable. Is this an nvidia-specific issue, or does this also affect mesa?

**Comment by nanonyme** [comment] 2020-04-09 22:07
This only affects the nVidia proprietary drivers.

**Comment by nanonyme** [comment] 2020-09-11 21:08
There is a solution for this https://blog.tingping.se/2018/08/26/flatpak-host-extensions.html but it requires participation from whoever is shipping your drivers. I'm going to close this one, there's nothing really that can be done in scope of this app.

**Closed by nanonyme** 2020-09-11 21:08 UTC
