### ISSUE TITLE
DOOM Eternal won't start on flatpaked Steam, but runs with steam from RPMFusion

### ISSUE THREAD

**Issue by vatula** [flathub/com.valvesoftware.Steam#560] opened 2020-05-09 13:53 UTC
**Game information**
DOOM Eternal. ID **782330**

**Distribution name and version where applicable**
Fedora 32

**Flatpak info**
flatpak --version: `Flatpak 1.6.3`
flatpak --gl-drivers:
```
nvidia-440-82
default
host
```
[steam-hw.txt](https://github.com/flathub/com.valvesoftware.Steam/files/4603546/steam-hw.txt)

**Problem description**
DOOM Eternal won't start on flatpaked Steam with Proton 5.0.7

**Does this issue reproduce with native Steam**
DOOM Eternal plays fine on native Steam installed from RPMFusion

Proton logs for the game are 3.7 GB. I have zipped them and uploaded to mega.nz. Here's the link: [steam-782330.zip](https://mega.nz/file/QsJxEYDL#kfW1IMz-cQdudkxoZRyqtnkgYVWtlPUO2XPXxvaZVHg)

I reported this issue here first: https://github.com/ValveSoftware/Proton/issues/3773 but then tested with native Steam which worked fine. @kisak-valve advised to raise issue here.

**Comment by nanonyme** [comment] 2020-06-21 19:54
Root cause supposedly here https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1057

**Comment by nanonyme** [comment] 2020-07-08 16:44
Can you try this with beta branch of this application? It's now using 20.08beta runtime.

**Comment by nanonyme** [comment] 2020-09-11 21:05
We're now on 20.08 stable. Is this still happening?

**Comment by MightyCreak** [comment] 2021-01-01 15:33
I still have the same issue  (I'm on Fedora 33)

**Comment by nanonyme** [comment] 2021-01-01 15:48
At this point I would suggest trying https://github.com/flathub/com.valvesoftware.Steam/wiki#Steam_Play_games_do_not_start_for_me since modern official Proton versions no longer work with this app.

**Comment by MightyCreak** [comment] 2021-01-01 18:51
It worked!

Here's what I did:
* In GNOME Software, I searched for Steam (with flatpak repo) and checked the "Proton (community build)" extensions:
    ![image](https://user-images.githubusercontent.com/6382548/103444607-cf507180-4c37-11eb-810f-30ad3dfabe89.png)
* Then I launched Steam, went to Steam > Settings > Steam Play, and selected "Proton 5.13-4 (community build 1608395899)"
* After being asked, I restarted Steam
    ![image](https://user-images.githubusercontent.com/6382548/103444636-2fdfae80-4c38-11eb-8bb1-c915388c8b31.png)
* Launched Doom, it worked as expected

One thing though, if I go back to the Settings window, the checkbox "Enable Steam Play for all other titles" is unchecked. Checking it again asks you again to restart Steam. The solution is to keep it as it is after the restart.. it works anyway :man_shrugging:

**Comment by nanonyme** [comment] 2021-01-01 19:46
The "Enable Steam Play for all other titles" thing disabling by itself has been reported earlier. It may be a bug in Steam itself.

**Comment by nanonyme** [comment] 2021-01-01 19:47
But great to hear you got the game to work.

**Comment by nanonyme** [comment] 2021-02-06 21:59
Closing, remaining things are tracked in other issues.

**Closed by nanonyme** 2021-02-06 21:59 UTC
