### ISSUE TITLE
"BROWSE LOCAL FILES..." doesn't work in clear linux os

### ISSUE THREAD

**Issue by romulasry** [flathub/com.valvesoftware.Steam#519] opened 2020-01-01 01:59 UTC
Anyone else have this bug?

**Comment by nanonyme** [comment] 2020-01-01 08:15
What does it do for you?

**Comment by gurtonbuster** [comment] 2020-01-06 05:27
I have the same problem. When I got to `Games > Add a Non-Steam game to my library`, I can't see all the folders and especially the folder where my second HDD is mounted.

**Comment by Xited** [comment] 2020-01-06 05:55
Did you installed steam from [Flatpak](https://www.flathub.org/apps/details/com.valvesoftware.Steam)?

**Comment by nanonyme** [comment] 2020-01-06 09:21
@gurtonbuster there is a sandboxed home inside .var/app/com.valvesoftware.Steam. The app cannot in general see outside it. Have you read FAQ? https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#i-want-to-add-external-disk-for-steam-libraries

>

**Comment by gurtonbuster** [comment] 2020-01-06 15:41
@nanonyme Whoops sorry I didn't see that. It works now.

**Comment by nanonyme** [comment] 2020-01-06 15:46
No worries. I'm still waiting a while for confirmation of whether the original posted had same issue as you before closing this though.

**Comment by monterrr** [comment] 2020-01-19 03:15
Duplicate of bug #480

**Comment by guihkx** [comment] 2021-02-24 04:42
This can be closed

**Closed** 2021-02-24 14:47 UTC
