### ISSUE TITLE
Steam crash on launch

### ISSUE THREAD

**Issue by aurium** [flathub/com.valvesoftware.Steam#778] opened 2021-06-10 03:39 UTC
If I try `flatpak run com.valvesoftware.Steam`, it crashes immediately after the Steam update dialog finish its progress.

I did uninstall and reinstall Steam, nothing changes.

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
$ flatpak --version
Flatpak 1.2.5
```

```
$ flatpak run com.valvesoftware.Steam
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/aurium
INFO:root:Overriding TZ to America/Bahia
Running Steam on org.freedesktop.platform 20.08.13 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/aurium/.local/share/Steam/ubuntu12_32/steam
[2021-06-10 00:21:34] Startup - updater built Jun  8 2021 22:23:36
Installing breakpad exception handler for appid(steam)/version(1623193086)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-06-10 00:21:35] Loading cached metrics from disk (/home/aurium/.local/share/Steam/package/steam_client_metrics.bin)
[2021-06-10 00:21:35] Using the following download hosts for Public, Realm steamglobal
[2021-06-10 00:21:35] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-10 00:21:35] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-10 00:21:35] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-06-10 00:21:35] Checking for update on startup
[2021-06-10 00:21:35] Checking for available updates...
[2021-06-10 00:21:35] Downloading manifest: https://cdn.cloudflare.steamstatic.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-06-10 00:21:35] Download skipped: /client/steam_client_ubuntu12 version 1623193086, installed version 1623193086, existing pending version 0
[2021-06-10 00:21:35] Nothing to do
[2021-06-10 00:21:35] Verifying installation...
[2021-06-10 00:21:35] Performing checksum verification of executable files
[2021-06-10 00:21:36] Verification complete
Loaded SDL version 2.0.15-6501165
Gtk-Message: 00:21:36.300: Failed to load module "gail"
Gtk-Message: 00:21:36.300: Failed to load module "atk-bridge"
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  12
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  13
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  14
xerror_handler: X failed, continuing
Installing breakpad exception handler for appid(steam)/version(1623193086)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Could not connect to X session manager: None of the authentication protocols specified are supported
[0610/002136.620612:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
[0610/002136.652076:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0610/002136.652146:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0610/002136.652151:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0610/002136.652156:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_datagram_based_create_source
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[0610/002136.697915:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0610/002136.697980:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0610/002136.697987:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0610/002136.697992:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0610/002136.699629:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
[0610/002136.724991:ERROR:sandbox_linux.cc(372)] InitializeSandbox() called with multiple threads in process gpu-process.
[0610/002136.766823:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0610/002136.766890:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0610/002136.766896:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0610/002136.766901:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0610/002136.768680:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
CApplicationManagerPopulateThread took 12 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
CAppInfoCacheReadFromDiskThread took 57 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)

(steam:164): GLib-GObject-CRITICAL **: 00:21:36.927: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Installing breakpad exception handler for appid(steam)/version(1623193086)
Proceed to auto login
Installing breakpad exception handler for appid(steam)/version(1623193086)
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
crash_20210610002136_20.dmp[255]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210610002136_20.dmp
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
Installing breakpad exception handler for appid(steam)/version(1623193086)
crash_20210610002134_1.dmp[259]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210610002134_1.dmp
/home/aurium/.local/share/Steam/steam.sh: line 772:   164 Segmentation fault      $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20210610002136_20.dmp[255]: Finished uploading minidump (out-of-process): success = yes
crash_20210610002136_20.dmp[255]: response: CrashID=bp-49e6f51c-e2d4-4b83-93be-6fc202210609
crash_20210610002136_20.dmp[255]: file ''/tmp/dumps/crash_20210610002136_20.dmp'', upload yes: ''CrashID=bp-49e6f51c-e2d4-4b83-93be-6fc202210609''
crash_20210610002134_1.dmp[259]: Finished uploading minidump (out-of-process): success = yes
crash_20210610002134_1.dmp[259]: response: CrashID=bp-88d69b70-23cd-4b9c-9e03-4ed0a2210609
crash_20210610002134_1.dmp[259]: file ''/tmp/dumps/crash_20210610002134_1.dmp'', upload yes: ''CrashID=bp-88d69b70-23cd-4b9c-9e03-4ed0a2210609''
```

**Comment by aghpub** [comment] 2021-06-10 07:50
Same error after the last update on Arch Linux.

**Comment by jorg-j** [comment] 2021-06-10 08:15
Same error on PopOS

```
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/jack/.var/app/com.valvesoftware.Steam
INFO:root:Overriding TZ to Australia/Melbourne
Running Steam on org.freedesktop.platform 20.08.13 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/jack/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam
[2021-06-10 18:13:38] Startup - updater built Jun  8 2021 22:23:36
Installing breakpad exception handler for appid(steam)/version(1623193086)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-06-10 18:13:38] Loading cached metrics from disk (/home/jack/.var/app/com.valvesoftware.Steam/.local/share/Steam/package/steam_client_metrics.bin)
[2021-06-10 18:13:38] Using the following download hosts for Public, Realm steamglobal
[2021-06-10 18:13:38] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-10 18:13:38] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-10 18:13:38] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-06-10 18:13:38] Checking for update on startup
[2021-06-10 18:13:38] Checking for available updates...
[2021-06-10 18:13:38] Downloading manifest: https://cdn.cloudflare.steamstatic.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-06-10 18:13:38] Download skipped: /client/steam_client_ubuntu12 version 1623193086, installed version 1623193086, existing pending version 0
[2021-06-10 18:13:38] Nothing to do
[2021-06-10 18:13:38] Verifying installation...
[2021-06-10 18:13:38] Performing checksum verification of executable files
[2021-06-10 18:13:39] Verification complete
Loaded SDL version 2.0.15-6501165
Gtk-Message: 18:13:40.296: Failed to load module "gail"
Gtk-Message: 18:13:40.296: Failed to load module "atk-bridge"
Gtk-Message: 18:13:40.296: Failed to load module "appmenu-gtk-module"
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  12
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  13
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  14
xerror_handler: X failed, continuing
Installing breakpad exception handler for appid(steam)/version(1623193086)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Could not connect to X session manager: None of the authentication protocols specified are supported
[0610/181340.610829:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
[0610/181340.658472:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0610/181340.658516:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0610/181340.658520:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0610/181340.658525:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_datagram_based_create_source
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
CApplicationManagerPopulateThread took 8 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
[0610/181340.718544:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0610/181340.718603:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0610/181340.718608:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0610/181340.718612:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
Installing breakpad exception handler for appid(steam)/version(1623193086)
[0610/181340.719877:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
CAppInfoCacheReadFromDiskThread took 45 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)

(steam:160): GLib-GObject-CRITICAL **: 18:13:40.806: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[0610/181340.828584:ERROR:sandbox_linux.cc(372)] InitializeSandbox() called with multiple threads in process gpu-process.
Installing breakpad exception handler for appid(steam)/version(1623193086)
Proceed to auto login
Installing breakpad exception handler for appid(steam)/version(1623193086)
[0610/181340.886908:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0610/181340.886963:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0610/181340.886970:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0610/181340.886974:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0610/181340.888257:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
crash_20210610181340_20.dmp[389]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210610181340_20.dmp
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
Installing breakpad exception handler for appid(steam)/version(1623193086)
crash_20210610181338_1.dmp[393]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210610181338_1.dmp
/home/jack/.var/app/com.valvesoftware.Steam/.local/share/Steam/steam.sh: line 772:   160 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20210610181340_20.dmp[389]: Finished uploading minidump (out-of-process): success = yes
crash_20210610181340_20.dmp[389]: response: CrashID=bp-ce0989ed-8e02-4cfd-b4ee-d35bf2210610
crash_20210610181340_20.dmp[389]: file ''/tmp/dumps/crash_20210610181340_20.dmp'', upload yes: ''CrashID=bp-ce0989ed-8e02-4cfd-b4ee-d35bf2210610''
crash_20210610181338_1.dmp[393]: Finished uploading minidump (out-of-process): success = yes
crash_20210610181338_1.dmp[393]: response: CrashID=bp-b8bc52d6-0e48-4e86-9b4c-91da42210610
crash_20210610181338_1.dmp[393]: file ''/tmp/dumps/crash_20210610181338_1.dmp'', upload yes: ''CrashID=bp-b8bc52d6-0e48-4e86-9b4c-91da42210610''
```

**Comment by smcv** [comment] 2021-06-10 10:54
This seems to be a Steam bug, not a bug in this Flatpak app. We don't know why it affects some systems and not others. It is unlikely that this Flatpak app will be able to solve it.

The assertion failure `src/public/tier1/utlmemory.h (176) : Assertion Failed: 0` seems to be characteristic.

ValveSoftware/steam-for-linux#7813 and ValveSoftware/steam-for-linux#7847 seem to be the same thing.

**Comment by aurium** [comment] 2021-06-10 13:52
I try Steam on docker, and it works:
```docker run -e DISPLAY=${DISPLAY} -v /dev/dri:/dev/dri -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/shm:/dev/shm -v /run/user/${UID}/pulse:/run/user/${UID}/pulse -v /etc/machine-id:/etc/machine-id -v ${HOME}/Downloads:/tmp/Downloads --privileged=true --name=steam tianon/steam```

**Comment by aghpub** [comment] 2021-06-10 13:52
Thank you for the links. Manually changing "RememberPassword" from "1" to "0" in registry.vdf as described in [the second link](https://github.com/ValveSoftware/steam-for-linux/issues/7847#issuecomment-858328101) seems to be a workarond until Valve releases an updated version. At least I was able to run Steam after that.

**Comment by erdnaxe** [comment] 2021-06-12 09:21
Same issue on NixOS 21.05, I updated my steam client yesterday and since then I am not able to run the flatpak anymore.
I changed `RememberPassword` to `0` in `registry.vdf` and now it's working fine.

**Comment by nanonyme** [comment] 2021-06-12 09:31
Please don't metoo on this thread. This is pinned since this is common issue and there are useful tips and links included.

**Comment by Pobega** [comment] 2021-06-21 13:50
Unsure if this is the same issue but on a fresh Fedora 34 install the Steam Flatpak has been crashing for me randomly while running. The error I see in `dmesg` is:

```
[42075.420078] CIPCServer::Thr[48873]: segfault at 40 ip 00000000f79b5f25 sp 00000000d9ced8cc error 4 in libc-2.31.so[f792d000+15d000]
[42075.420086] Code: 40 38 ca 0f 84 4d 01 00 00 80 f9 00 0f 84 71 01 00 00 40 4f 75 14 8a 08 38 ca 0f 84 36 01 00 00 80 f9 00 0f 84 5a 01 00 00 40 <8b> 08 bd ff fe fe fe bf ff fe fe fe 01 cd 31 cd 01 cf 8d 40 04 0f
```

**Comment by smcv** [comment] 2021-08-03 11:41
The crash that could be worked around by setting `RememberPassword` to `0` was a Steam bug. It has been fixed in Steam.

The crash involving `src/public/tier1/utlmemory.h (176) : Assertion Failed: 0` was the same thing. It has been fixed in Steam.

I think this issue should probably be closed, so we can have a separate issue for any subsequent crashes on startup?

**Closed** 2021-08-03 15:27 UTC
