### ISSUE TITLE
Games using SDL-image fail to launch

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/com.valvesoftware.Steam#417] opened 2019-08-15 21:52 UTC
**Game information**
Shadow of mordor

**Distribution name and version where applicable**
$ cat /etc/os-release
NAME=Fedora
VERSION="30.20190814.0 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30.20190814.0 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
OSTREE_VERSION=30.20190814.0

-->

**Flatpak info**

**Problem description**
do not open

log
 https://paste.fedoraproject.org/paste/a24qSmlATA7aZw95GkSCJw/deactivate/5zlXh97pUGG16ietkQgiTsVW3iSxjlVJhbSwCsahwp4Mccfgoy4gtqpFOsNB2A3m

**Does this issue reproduce with native Steam**

**Comment by nanonyme** [comment] 2019-08-16 05:22
I get warnings about deactivating the paste when trying to open it. Maybe use a gist instead?

**Comment by FastOSlinux** [comment] 2019-08-18 21:55
> I get warnings about deactivating the paste when trying to open it. Maybe use a gist instead?

I don't understand, but it's something with my partition, because other games in the same location are not opening

**Comment by FastOSlinux** [comment] 2019-08-19 19:19
I moved to another partition and still the same problem

Loaded Config for Local Selection Path for App ID 241930, Controller 0: /var/home/fastos/.local/share/Steam/steamapps/workshop/content/241100/485450955/701784661372096826_legacy.bin
Loaded Config for Local Override Path for App ID 241930, Controller 0: /var/home/fastos/.local/share/Steam//controller_base/empty.vdf
GameAction [AppID 241930, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 241930, ActionID 3] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 241930, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 241930, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 241930, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 241930, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 241930 "", ProcID 444, IP 0.0.0.0:0
Starting app 241930
Loaded Config for Local Selection Path for App ID 241930, Controller 0: /var/home/fastos/.local/share/Steam/steamapps/workshop/content/241100/485450955/701784661372096826_legacy.bin
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Loaded Config for Local Override Path for App ID 241930, Controller 0: /var/home/fastos/.local/share/Steam//controller_base/empty.vdf
>>> Adding process 444 for game ID 241930
GameAction [AppID 241930, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 454 != 450, skipping destruction (fork without exec?)
pid 453 != 450, skipping destruction (fork without exec?)
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 241930, ActionID 3] : LaunchApp changed task to Completed with ""
>>> Adding process 445 for game ID 241930
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 446 for game ID 241930
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 450 for game ID 241930
/var/mnt/ba9bc4fd-8849-4ca0-9e5c-744c157e2184/jogos3/steamapps/common/ShadowOfMordor/bin/ShadowOfMordor: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWread
>>> Adding process 456 for game ID 241930
>>> Adding process 457 for game ID 241930
Game removed: AppID 241930 "", ProcID 444 
Exiting app 241930
JS method call Messaging.PostMessage with 4 arguments
JS method call Messaging.PostMessage with 4 arguments
JS method call Messaging.PostMessage with 4 arguments

**Comment by nanonyme** [comment] 2019-08-19 19:43
/usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWread looks like the root cause

**Comment by nanonyme** [comment] 2019-08-19 19:50
https://www.libsdl.org/tmp/SDL/WhatsNew.txt
* The SDL_RW* macros have been turned into functions that are available only in 2.0.10 and onward

**Comment by nanonyme** [comment] 2019-08-19 19:55
I suggest using beta branch of this app. It's not clear whether SDL2 2.0.10 will land in runtime 18.08. Runtime 19.08 will be released quite soon and will fix this.

**Comment by FastOSlinux** [comment] 2019-08-20 21:54
> I suggest using beta branch of this app. It's not clear whether SDL2 2.0.10 will land in runtime 18.08. Runtime 19.08 will be released quite soon and will fix this.

I tried the beta with ACO (https://valentindavid.com/posts/2019-07-04-testing-mesa-aco-with-flatpak/) but had the same error, anyway i wait for the update, thanks

**Comment by valentindavid** [comment] 2019-08-21 10:05
It looks to me that the Steam runtime also has 2.0.9. The developers should have not linked against 2.0.10.

**Comment by nanonyme** [comment] 2019-08-21 13:16
Makes me wonder if there's some process issue in Steam with developers getting access to newer SDK's than are released.

**Comment by FastOSlinux** [comment] 2019-09-06 00:02
any updates?

**Comment by nanonyme** [comment] 2019-09-06 09:53
You can for now use beta of this app. Runtime version 19.08 is not yet released.

**Comment by FastOSlinux** [comment] 2019-09-06 21:15
$ flatpak --user info com.valvesoftware.Steam//beta

Steam - Jogue jogos populares e os últimos lançamentos

        ID: com.valvesoftware.Steam
       Ref: app/com.valvesoftware.Steam/x86_64/beta
      Arq.: x86_64
      Ramo: beta
    Versão: 1.0.0.61
   Licença: LicenseRef-proprietary
    Origem: flathub-beta
   Coleção: org.flathub.Beta
Instalação: user
 Instalado: 68,5 MB
   Runtime: org.freedesktop.Platform/x86_64/19.08beta
       Sdk: org.freedesktop.Sdk/x86_64/19.08beta

    Commit: 064ee170859fda37ad6941cf10b8c08a674b112a9486c7a42f5a306643e87e2e
       Pai: 387da7d7fa5932522e8864a307cc8cb44326ed2c30bbb2a9ad61f797716c0bda
   Assunto: Bump shared-library-guard (07f75197)
      Data: 2019-08-28 06:58:24 +0000


$FLATPAK_GL_DRIVERS=mesa-aco flatpak run com.valvesoftware.Steam//beta
GameAction [AppID 241930, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 241930, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 241930, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 241930, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 241930, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 241930, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 241930 "", ProcID 460, IP 0.0.0.0:0
Starting app 241930
>>> Adding process 460 for game ID 241930
GameAction [AppID 241930, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 241930, ActionID 2] : LaunchApp changed task to Completed with ""
>>> Adding process 461 for game ID 241930
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 472 != 468, skipping destruction (fork without exec?)
pid 471 != 468, skipping destruction (fork without exec?)
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 462 for game ID 241930
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/fastos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 468 for game ID 241930
>>> Adding process 474 for game ID 241930
/var/mnt/ba9bc4fd-8849-4ca0-9e5c-744c157e2184/jogos3/steamapps/common/ShadowOfMordor/bin/ShadowOfMordor: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWread
>>> Adding process 475 for game ID 241930
Game removed: AppID 241930 "", ProcID 460 
Exiting app 241930
No cached sticky mapping in ActivateActionSet.JS method call Messaging.PostMessage with 4 arguments
JS method call Messaging.PostMessage with 4 arguments
JS method call Messaging.PostMessage with 4 arguments
Installing breakpad exception handler for appid(steam)/version(1566431379)
Installing breakpad exception handler for appid(steam)/version(1566431379)
Installing breakpad exception handler for appid(steam)/version(1566431379)
Installing breakpad exception handler for appid(steam)/version(1566431379)
Installing breakpad exception handler for appid(steam)/version(1566431379)
Installing breakpad exception handler for appid(steam)/version(1566431379)
Installing breakpad exception handler for appid(steam)/version(1566431379)
Installing breakpad exception handler for appid(steam)/version(1566431379)
Installing breakpad exception handler for appid(steam)/version(1566431379)

**Comment by nanonyme** [comment] 2019-09-10 20:47
Stable version of this app now uses 19.08. Would be worth trying again.

**Comment by FastOSlinux** [comment] 2019-09-11 22:00
> Stable version of this app now uses 19.08. Would be worth trying again.

still the same


$ flatpak run com.valvesoftware.Steam
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Overriding TZ to America/Sao_Paulo
Running Steam on org.freedesktop.platform 19.08.0 64-bit
.......

Grid autosport
/var/mnt/ba9bc4fd-8849-4ca0-9e5c-744c157e2184/jogos3/steamapps/common/GRID Autosport/bin/GridAutosport: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWread

Shadow of mordor
/var/mnt/ba9bc4fd-8849-4ca0-9e5c-744c157e2184/jogos3/steamapps/common/ShadowOfMordor/bin/ShadowOfMordor: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWread

**Comment by FastOSlinux** [comment] 2019-09-13 21:08
> Workaround should land in stable in a matter of hours.

working for shadow of mordor, but not for grid autosport

**Comment by drBlaze** [comment] 2019-09-13 21:13
Also not for Total War: Warhammer, Alien: Isolation and Company of Heroes 2

**Comment by aaron-tolmaci** [comment] 2019-09-14 00:14
Also not for Deus Ex: Mankind Divided.

**Comment by nanonyme** [comment] 2019-09-14 07:08
Do all those have same issue? We have some plans for a more generic workaround. Note that this is a Steam bug that will happen on all distros with native Steam soon.

**Comment by drBlaze** [comment] 2019-09-14 08:34
> Do all those have same issue?
`~/.local/share/Steam/steamapps/common/Total War WARHAMMER/bin/TotalWarhammer: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWread`
`~/.local/share/Steam/steamapps/common/Alien Isolation/bin/AlienIsolation: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWread`
`~/.local/share/Steam/steamapps/common/Company of Heroes 2/bin/CompanyOfHeroes2: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWread`

**Comment by nanonyme** [comment] 2019-09-14 11:02
Looks like. It will require changes in shared-library-guard pattern matching to make a generic solution.

**Comment by nanonyme** [comment] 2019-09-15 07:50
Pending https://gitlab.com/freedesktop-sdk/shared-library-guard/merge_requests/13

**Comment by nanonyme** [comment] 2019-09-17 09:43
While we can now implement the more wide workaround even now, I would prefer landing config-driven blocked list generation first as otherwise end result will be quite hard to read.

**Comment by nanonyme** [comment] 2019-09-17 21:50
Will roll a release of shared-library-guard after this is merged https://gitlab.com/freedesktop-sdk/shared-library-guard/merge_requests/14, rewrite configs and do the generic workaround.

**Comment by lentzi90** [comment] 2019-09-18 16:45
I think I'm having the same problem with Battle for Wesnoth. It does not work on the latest commit (`229827a096e121d3c66f6cdfde49408618d9c33da4d0cdf9b7dfe86e93cd6e1f`), but works fine if I do this:
```
sudo flatpak update --commit=474cb9db7e88ba8cc1428beae5d758b76d3d77f41e182ef7e3239048181aab40 com.valvesoftware.Steam
```

I see the same log messages about "symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0: undefined" in the logs as reported here. Battle for Wesnoth is free btw so please try it and confirm if you are seeing the same.

**Comment by nanonyme** [comment] 2019-09-18 18:39
This is a generic bug in Steam that is going to happen on basically all distros that release after this Fall with native Steam. If you want to give samples, providing path to executable might be useful evaluating effectiveness of the workaround which is going to be deployed soon. If you found a working commit, it's most likely before the runtime update to 19.08.

**Comment by nanonyme** [comment] 2019-09-18 20:20
Actually that example *was* useful. It's a lot smaller game than the one I've been hacking this with.

**Comment by Darklink999999** [comment] 2019-09-23 04:44
Hello, I have the same problem with Tomb Raider (2013). any workarounds for that?

**Comment by nanonyme** [comment] 2019-09-23 21:09
I have been informed Steam beta contains fix to this issue. If anyone could test and report results to linked issue, it would be useful.

**Comment by FastOSlinux** [comment] 2019-09-23 22:49
upstream fixed?
Linux:

    Fix titles depending on SDL_image not working on distros that use SDL2 2.0.10
 
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1589131508782140065

**Comment by FastOSlinux** [comment] 2019-09-23 22:59
with beta grid autosport works

**Comment by nanonyme** [comment] 2019-10-02 17:20
I added generic workaround for now since it may take some time until the change hits stable on Steam side.

**Comment by nanonyme** [comment] 2019-10-17 17:06
The generic workaround is causing too much noise. I'm going to revert it and start adding game by game workarounds.

**Comment by tidux** [comment] 2020-11-06 07:41
This also impacts Final Fantasy X/X-2 HD Remaster.

**Comment by marekolsak** [comment] 2020-11-17 16:41
Grid Autosport and Shadow Of Mordor don't work with Steam beta.

**Comment by ArturLinhart** [comment] 2020-11-25 13:42
I have now the similar problem with XCom2 on Debian Linux:

/Forbes/Steam/SteamLibrary/steamapps/common/XCOM 2/bin/XCOM2: symbol lookup error: /home/user/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libSDL2_image-2.0.so.0: undefined symbol: SDL_RWseek

**Comment by nanonyme** [comment] 2020-11-25 16:29
Is there another release of SDL2?

**Comment by nanonyme** [comment] 2020-11-25 16:32
https://github.com/ValveSoftware/steam-for-linux/issues/6488 was the original bug I reported against Steam.

**Comment by nanonyme** [comment] 2020-11-25 16:35
Ah, this is actually same issue in reverse. Earlier SDL2 was pinned but not libSDL2_image. Now it's the reverse. Please provide listing of ls -l /home/user/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/

**Comment by marekolsak** [comment] 2020-12-10 21:35
I had libSDL in /usr/local/lib/. After removing that, Grid Autosport is working again.

**Closed** 2022-06-03 18:42 UTC
