### ISSUE TITLE
Torchligt 2 - crash on start

### ISSUE THREAD

**Issue by Pshemas** [flathub/com.valvesoftware.Steam#95] opened 2018-06-11 22:21 UTC
With this one I'm not sure it is flatpak package related as it seems it is not working in general (need to test on a machine with  a configuration I know worked), but just in case here's the CLI output:

```
[AppID 200710, ActionID 5] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 200710, ActionID 5] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 200710, ActionID 5] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask: 30
Game update: AppID 200710 "", ProcID 756, IP 0.0.0.0:0
>>> Adding process 756 for game ID 200710
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/przemek/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/przemek/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/przemek/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Torchlight II/ModLauncher.bin.x86_64: symbol lookup error: /lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
GameAction [AppID 200710, ActionID 5] : LaunchApp changed task to Completed with ""
>>> Adding process 757 for game ID 200710
Game removed: AppID 200710 "", ProcID 756 
No cached sticky mapping in ActivateActionSet.
```

Side note - you rock guys. After upgrading my system I found out that Steam runtime provided in the repos for my distro causes a bit of issues. Flatpak to the rescue - majority of the games work great.

**Comment by mczimmermann** [comment] 2018-06-13 14:47
I had a similar problem with Torchlight, the solution was to delete (better move or rename) libfreetype.so in 

~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Torchlight II/lib
~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Torchlight II/lib64

Although renaming the one in lib64 could be enough ...

**Comment by pshpsh** [comment] 2018-06-15 22:46
LD_PRELOAD=~/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libfontconfig.so.1 %command%

**Comment by Pshemas** [comment] 2018-06-22 18:45
@pshpsh : you're the man. That allowed the game to start - but sadly exactly as with Rise of the Tom Raider I have no sound (reported in other post). Will try to check it later on and see whether I get the same :
Cannot access file /etc/alsa-pulse.conf
type of error with it too.

**Comment by nanonyme** [comment] 2018-08-05 15:27
The libfontconfig mess sounds like a game issue to me

**Comment by valentindavid** [comment] 2018-08-21 22:48
I got confused. The game provides `lib64/libfreetype.so.6` which is bad. Please remove it manually.

**Comment by valentindavid** [comment] 2018-08-21 22:49
There is not much we can do for this one. The game should not play with LD_LIBRARY_PATH and provide system libraries. I propose we close this issue.

**Comment by nanonyme** [comment] 2018-08-27 05:40
@valentindavid technically we could set LD_PRELOAD in the wrapper but then there's Steam vs FDO runtime version of this file

**Comment by nanonyme** [comment] 2018-08-27 05:48
But yeah, @Pshemas we need to find a way to make game vendor and Valve aware of thid. This is clearly a broken game

**Comment by nanonyme** [comment] 2018-08-27 16:06
Might not be right project but might get some interest in the issue and possibly directions to right place...

**Comment by nanonyme** [comment] 2018-08-27 17:43
Okay. So the problem is the game vendor went defunct in 2017 so there isn't really anyone around to fix this

**Comment by nanonyme** [comment] 2018-09-07 07:16
@valentindavid had some ideas on making a maintainable library blacklist. Once it's included, we should see if this be made to work out of the box

**Comment by nanonyme** [comment] 2018-09-10 16:18
Tracking ticket https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/496

**Comment by nanonyme** [comment] 2018-09-10 22:32
Turns out that https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting has a fairly wide list of broken games that would also need this workaround

**Comment by nanonyme** [comment] 2018-12-10 20:20
Did this game use bash for its wrapper?

**Comment by PureW** [comment] 2019-02-20 02:38
> LD_PRELOAD=~/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libfontconfig.so.1 %command%

:+1:  This is enough to get Civilization 6 running too.

**Comment by nanonyme** [comment] 2019-02-20 07:31
Could you try if SHARED_LIBRARY_GUARD=1 (or 2) makes the game run? It's a prototype audit library.

**Comment by nanonyme** [comment] 2019-02-20 07:35
I'm going to document this a bit later. Basically mode 1 should block these libraries, mode 2 may prevent glibc from enabling library profiling which is bad for runtime performance.

**Comment by nanonyme** [comment] 2019-02-20 08:01
Civilization 6 needs adding to https://github.com/flathub/com.valvesoftware.Steam/blob/master/freedesktop.ld.so.blockedlist

**Comment by PureW** [comment] 2019-02-26 00:16
@nanonyme Merely inputting `SHARED_LIBRARY_GUARD=1` in launch options for Civ 6 leads to the same issue as earlier with the undefined function.

**Comment by nanonyme** [comment] 2019-02-26 06:56
As said, for Civ 6 someone who has the game needs to contribute data to above file. Otherwise it will not help.

**Comment by PureW** [comment] 2019-02-26 16:34
@nanonyme I could do it. Is there documentation anywhere on that file?

**Comment by nanonyme** [comment] 2019-02-26 16:41
It's basically a form of pattern matching with executable name on left side and bad library on right side. Your files are somewhere under .var/app/com.valvesoftware.Steam sandbox directory

You can use the existing ones as examples.

**Closed** 2019-05-26 12:26 UTC
Labels: game issue
