### ISSUE TITLE
Custom proton builds not found

### ISSUE THREAD

**Issue by aDogCalledSpot** [flathub/com.valvesoftware.Steam#516] opened 2019-12-07 12:59 UTC
I installed Proton-GE as described on their GitHub. I extracted the release tarball into `~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d`. I now have the following structure:

```
compatibilitytools.d/Proton-4.21-GE-1/
- compatibilitytool.vdf
- dist/
- filelock.py
- LICENSE
- proton
- proton_3.7_tracked_files
- protonfixes/
- __pychache__/
- toolmanifest.vdf
- user_settings.sample.py
- version
```

I tried symlinking the folder to `~/.var/app/com.valvesoftware.Steam/.steam/root/compatibilitytools.d` and `~/.steam/root/compatibilitytools.d` but that didn't work either.

When starting Steam from the command line I do not get any output relating to custom Proton versions.

**Comment by nanonyme** [comment] 2019-12-07 13:49
@gasinvein any clue?

**Comment by gasinvein** [comment] 2019-12-07 13:58
@aDogCalledSpot Should it actually print anything? Check setting instead.

**Comment by aDogCalledSpot** [comment] 2019-12-07 14:04
I dont know if it should print anything, I just assumed it would since the output is otherwise quite verbose.

Under the settings it isn't appearing in the drop-down menu. Anything else I can check?

**Comment by gasinvein** [comment] 2019-12-07 14:26
I can't reproduce it, sorry. Proton-4.21-GE-1 appears for me in the drop-down lists as expected.

**Comment by nanonyme** [comment] 2019-12-08 21:16
Does it work correctly outside Steam beta already?

**Comment by gasinvein** [comment] 2019-12-11 18:38
@nanonyme AFAIK yes, all related changes landed in Steam client release some time ago, including support for system-wide compat tool installations.

**Comment by Saroufim** [comment] 2019-12-18 15:29
I have a similar issue. The proton builds are found but launching any game from Proton-GE-4.21+ simply opens the archive manager.

**Comment by monterrr** [comment] 2020-01-19 13:50
Doesn't work because you must have downloaded the wrong file with the source code instead of the actual build.

**Comment by aDogCalledSpot** [comment] 2020-01-19 19:12
@monterrr this isn't the case. Compare the files I mentioned with the source code of Proton-GE, they are very different.

**Comment by monterrr** [comment] 2020-01-19 21:45
Then I don't know what the problem is, It was me that wrote the information on how to install Proton-GE  in the flatpak steam and made a pull request, as far as I know it it correct and works for me as too for other people that have tested.

**Comment by monterrr** [comment] 2020-01-31 15:08
Have you tried more than one different versions of proton ge?
Proton-GE-4.21 had that bug that executed the archive manager but that has now been fixed by Proton-5.0-GE-1 that has been released recently, but this version release download when extracted has one folder more than needed that prevents Proton-5.0-GE-1 from showing on steam, simply don't extract the first folder but the second instead into compatibilitytools.d

**Comment by TiZ-EX1** [comment] 2020-05-18 06:33
This is working correctly with me, using Proton-5.8-GE-2. I beat Spyro Reignited 1 on Flatpak Steam with pre-rendered cutscenes and all.

**Comment by nanonyme** [comment] 2020-09-11 21:12
If this still reproduces, please re-open.

**Closed by nanonyme** 2020-09-11 21:12 UTC
