### ISSUE TITLE
Insurgency won't start in Linux

### ISSUE THREAD

**Issue by andres-jurado** [flathub/com.valvesoftware.Steam#135] opened 2018-08-17 22:31 UTC
OS: Ubuntu 18.04 64-bit
Steam installed as flatpak
Drivers: Mesa 18.3

Hardware:
CPU: Ryzen 7 1700
RAM: 32 GB
GPU: AMD RX 580 8 GB

Issue: when selecting play on insurgency "running" is displayed briefly, but nothing else happens. Insurgency doesn't start.

**Comment by nanonyme** [comment] 2018-08-18 19:53
Considering we have #83 open, this sounds like a regression. Note that host Mesa isn't used with flatpak.

**Comment by valentindavid** [comment] 2018-08-21 20:34
This is a bug from the game. They provide an old `libgcc_s.so.1` in the LD_LIBRARY_PATH. Please remove manually the file `bin/libgcc_s.so.1` from the installation directory. There is not much we can do on this one.

**Comment by nanonyme** [comment] 2018-08-21 20:40
May wish to file an upstream bug about this.

**Comment by pablodav** [comment] 2018-09-19 05:43
just testing: it still doesn't works.

```
>>> Adding process 309 for game ID 222880
ERROR: ld.so: object '/home/pablo/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 311 for game ID 222880
>>> Adding process 312 for game ID 222880
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
JS method call Parental.RegisterForParentalSettingsChanges with 1 arguments
JS method call Broadcast.RegisterForBroadcastStatus with 1 arguments
JS method call Broadcast.RegisterForViewerRequests with 1 arguments
JS method call SharedConnection.RegisterOnMessageReceived with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
>>> Adding process 313 for game ID 222880
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
SDL video target is 'x11'

Failed to create GL context: Unable to make GL context current
SDL video target is 'x11'
Failed to create GL context: Unable to make GL context current/home/pablo/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/insurgency2/insurgency.sh: línea 65:   313 Violación de segmento  (`core' generado) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "-game insurgency" "$@"
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsg with 2 arguments
Installing breakpad exception handler for appid(steam)/version(1536436120)
Game removed: AppID 222880 "", ProcID 308 
```
Also affects "Day of Infamy" with same error as it is built on top of same game base.

**Comment by nanonyme** [comment] 2018-09-19 06:27
Library blacklist is under work, we'll workaround these on game to game basis both once it's done

**Comment by nanonyme** [comment] 2018-10-15 15:29
@valentindavid I guess I could add LD_LIBRARY_PRELOAD for FD.o libstdc++.so.6 until we manage to stabilize the blocked list. Can you think of any downsides from this?

**Comment by nanonyme** [comment] 2019-01-25 21:57
Could someone figure out what the actual name of the game binary is so I can write a blocked list rule?

**Comment by nanonyme** [comment] 2019-02-06 21:42
Could try this after updating Steam. Not sure if the mapping is correct due to lack of feedback and the fact I don't own this game.

 flatpak run --env=SHARED_LIBRARY_GUARD=2 com.valvesoftware.Steam

**Comment by mradermaxlol** [comment] 2019-06-30 10:14
@nanonyme tried running Steam the way you suggested, but everything Steam-network-related just didn't work (the "Friends" window didn't even open, offline status, webbrowser tabs didn't load, etc), in-game as well. It's also strange that Insurgency seems to be able to connect to its own servers or whatever, as the "Players in-game" count seems to work properly.
Here is the console output: [output.txt](https://github.com/flathub/com.valvesoftware.Steam/files/3342754/output.txt)

**Comment by valentindavid** [comment] 2019-06-30 14:25
I expected this to be fixed by 1280ce3aafa519b5c2450299e52424f59df5db50. Maybe there are more things to add there.

**Comment by mradermaxlol** [comment] 2019-06-30 14:46
> I expected this to be fixed by [1280ce3](https://github.com/flathub/com.valvesoftware.Steam/commit/1280ce3aafa519b5c2450299e52424f59df5db50). Maybe there are more things to add there.

Maybe. By the way, does the distro matter? I'm using Fedora 30 - just in case.

**Comment by valentindavid** [comment] 2019-06-30 14:48
Distribution should not matter in this case.

**Comment by t3kg33k** [comment] 2019-09-01 12:35
Are there any updates to this yet? Any fixes for Insurgency not starting?
I just loaded Fedora 30 for the first time on my gaming PC and it doesn't work. Worked just fine in PopOS 19.

**Comment by t3kg33k** [comment] 2019-09-21 10:53
I ended up removing _libgcc_s.so.1_ as @valentindavid recommended and it worked for me.

**Comment by nanonyme** [comment] 2019-09-21 10:57
It should no longer be required.

**Closed** 2019-10-01 16:26 UTC
Labels: game issue

**Comment by QmwJlHuSg9pa** [comment] 2023-02-26 09:10
As @pablodav mentioned, Day of Infamy is similarly affected by this issue (renaming the `libgcc_s.so.1` file does indeed allow the game to launch). As far as I can tell, DoI did not get a blacklist entry, unlike Insurgency: https://github.com/flathub/com.valvesoftware.Steam/blob/master/resources/blocklist/insurgency2.yml

**Comment by nanonyme** [comment] 2023-02-26 10:02
Please don't resurrect old issues. Feel free to open PR, Flathub will create test build that can be installed.
