### ISSUE TITLE
Distorted cracking sound in native games

### ISSUE THREAD

**Issue by andreldmonteiro** [flathub/com.valvesoftware.Steam#514] opened 2019-11-29 17:13 UTC
**Game information**
Tested with Life of Pixel, Rise of the Tomb Raider, Type:Rider - all native Linux versions and the problem appears on them using the flatpak steam version, this problem must affect many more games thought.

**Distribution name and version where applicable**
Fedora 31

**Flatpak info**
Flatpak 1.4.3
nvidia-440-36
default
host

**Problem description**
Right after launching the games when there is sound it is distorted.

**Does this issue reproduce with native Steam**
I have tested Life of Pixel using steam without flatpak and the issue doesn't happen.
Setting "PULSE_LATENCY_MSEC=60 %command%" as launch option fixes the problem for all three games.

**Comment by monterrr** [comment] 2019-12-26 18:32
@nanonyme I have found a solution - setting "PULSE_LATENCY_MSEC=60 %command%" as launch option fixes the problems, does this knowledge helps fixing flatpak steam?

**Comment by nanonyme** [comment] 2019-12-26 22:07
Possibly duplicate of https://github.com/flathub/com.valvesoftware.Steam/issues/426

**Comment by fabriciojardim** [comment] 2020-04-20 19:17
Same issue with _"Pillars of Eternity"_ and _"Prison Architect"_, both native.

The issue only occurs on Steam Flatpak and the above workaround solved it.

Not all native games I tried run into this, _"Darkest Dungeon"_ and _"FTL: Faster Than Light"_ worked just fine without any launch options.

**System**
Fedora 31
Flatpak 1.4.4
AMDGPU - Mesa

**Comment by dariox86** [comment] 2020-05-12 18:14
Same problem with Mark of the Ninja. Setting `PULSE_LATENCY_MSEC=60 %command%` fixes the issue. I don't remember having this problem with native Steam.

**Comment by nanonyme** [comment] 2020-09-11 21:08
Does this still reproduce now that we're on freedesktop-sdk 20.08?

**Comment by monterrr** [comment] 2020-09-11 22:27
Still the same.

**Comment by dariox86** [comment] 2020-09-11 22:38
Same here.

**Comment by fabriciojardim** [comment] 2020-09-12 14:36
Prison Architect still the same.

**Comment by KeironO** [comment] 2020-11-21 18:53
Hey there,

I think a recent update to Fedora is causing audio issues across Flatpak, and maybe the system as a whole.

Just posting it here so people know, although I know it's not exactly within your wheelhouse to deal with it.

BW,

KeironO

**Comment by Pshemas** [comment] 2020-12-24 20:00
Experiencing the same on OpenSUSE Tumbleweed. But it is not consistent - sometimes I get it, sometimes I don't . For me the best testing scenario turned out to be "Rise of the Tomb Raider" - most of the times I get the weird crackling sounds there.
With "PULSE_LATENCY_MSEC=60 %command%"  it appears to be gone.

**Comment by nanonyme** [comment] 2020-12-24 20:36
So let me get this straight: does `flatpak run --env=PULSE_LATENCY_MSEC=60 com.valvesoftware.Steam` help?

**Comment by Pshemas** [comment] 2020-12-29 12:54
@nanonyme : running the game by setting extra launch options "PULSE_LATENCY_MSEC=60 %command%" seems to "fix" crackling sounds. I guess it does the similar thing to the command you've given, but with exception it sets the variable when launching a given game, not Steam.

**Comment by monterrr** [comment] 2020-12-29 13:25
@nanonyme Yes that also solves the problem, tested with super life of pixel.

**Comment by nanonyme** [comment] 2020-12-29 13:56
@Pshemas I'm just considering we set that as default for entire app.

**Comment by monterrr** [comment] 2020-12-31 00:07
I'm going to close this since it's fixed with the new build, tested with super life of pixel.

But I have a question, setting this to all games could have other unintended consequences?

**Comment by monterrr** [comment] 2021-01-08 14:28
Reopening due to commit revert.

**Comment by nanonyme** [comment] 2021-01-08 14:56
I don't think there is anything that can be done about this. Maybe worth testing if reproduces with Pipewire running as system sound service instead of PulseAudio. If yes, debugging there.

**Comment by dariox86** [comment] 2022-07-03 22:03
As suggested by @nanonyme, this issue is gone for me with PipeWire for PulseAudio client. Tested with Mark of the Ninja.

**Closed** 2022-07-04 05:03 UTC
