### ISSUE TITLE
Steam Store tab not rendering correctly on launch

### ISSUE THREAD

**Issue by ciandonovan** [flathub/com.valvesoftware.Steam#944] opened 2022-08-30 16:00 UTC
**Distribution name and version where applicable**

Linux Mint 21

**Flatpak info**

flatpak --version: `Flatpak 1.12.7`
flatpak --gl-drivers: `default host`

```
Steam - Launcher for the Steam software distribution service

          ID: com.valvesoftware.Steam
         Ref: app/com.valvesoftware.Steam/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.0.74
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 43.2 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 5ed80483da0196d5be5e455cb841940c9f8b6f651820b6f5942a93cb310e7cde
      Parent: 25ec6a8b6a31e88c898fbacaa991b2ce37a5b97a2c8ff6a05332c35e7f9c0140
     Subject: Remove lsb_release from app (4b219afd)
        Date: 2022-07-02 11:04:13 +0000
```

**Problem description**

![Screenshot from 2022-08-30 16-46-23](https://user-images.githubusercontent.com/94260580/187484336-5e9cc037-0e47-4e75-ac17-cb71bab25975.png)

When opening the Steam Flatpak, the default Store page is almost completely blank as shown.

Switching to another tab such as Library, and then switching back to the Store page forces it to reload and render correctly.

This issue was reproduced with a completely fresh install of the Steam Flatpak. 

**Does this issue reproduce with native Steam**

No

**Comment by nanonyme** [comment] 2022-08-30 17:01
Please see if this reproduces with https://github.com/flathub/com.valvesoftware.Steam/issues/944

**Comment by ciandonovan** [comment] 2022-08-30 17:20
> Please see if this reproduces with #944

Is #944 not this issue?

**Comment by nanonyme** [comment] 2022-08-30 17:48
Sorry, clipboard error. I meant https://github.com/flathub/com.valvesoftware.Steam/wiki/Using-beta-branch-of-this-app.

**Comment by jbalme** [comment] 2022-09-02 17:47
> Sorry, clipboard error. I meant https://github.com/flathub/com.valvesoftware.Steam/wiki/Using-beta-branch-of-this-app.

Beta Steam flatpak seems to not have this problem. Thanks.

**Comment by nanonyme** [comment] 2022-09-02 20:05
Stable app was bumped to freedesktop-sdk 22.08 since yesterday so closing as fixed. You can run flatpak update to obtain latest version.

**Closed by nanonyme** 2022-09-02 20:05 UTC
