### ISSUE TITLE
Steam flatpak crash on startup: Error "steamwebhelper is not responding". (Last Ubuntu apparmor upgrade issue).  FIXED

### ISSUE THREAD

**Issue by webxon** [flathub/com.valvesoftware.Steam#1318] opened 2024-07-12 08:14 UTC
Yesterday I have running Steam fine, but when I have trying it to startup after few hours its throw me error: "steamwebhelper is not responding".
I have tried, but nothing help:
- flatpak run com.valvesoftware.Steam -clearbeta
- flatpak run com.valvesoftware.Steam --reset
- reinstalling Steam from flatpak store

Error (console):
[INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki](steam://openurl_external/https://steamcommunity.com/linkfilter/?u=http%3A%2F%2FINFO%3Aroot%3Ahttps%3A%2F%2Fgithub.com%2Fflathub%2Fcom.valvesoftware.Steam%2Fwiki)
INFO:root:Will set XDG dirs prefix to [/home/user/.var/app/com.valvesoftware.Steam](steam://openurl_external/https://steamcommunity.com/linkfilter/?u=http%3A%2F%2Fhome%2Fuser%2F.var%2Fapp%2Fcom.valvesoftware.Steam)
DEBUG:root:Checking input devices permissions
DEBUG:root:Addding /usr/lib/extensions/vulkan/gamescope/bin to PATH
DEBUG:root:Addding /usr/lib/extensions/vulkan/MangoHud/bin to PATH
steam.sh[2]: Running Steam on org.freedesktop.platform 23.08 64-bit
steam.sh[2]: STEAM_RUNTIME is enabled automatically
setup.sh[75]: Steam runtime environment up-to-date!
steam.sh[2]: Steam client's requirements are satisfied
[2024-07-11 16:19:57] Startup - updater built Jun 20 2024 17:13:49
[2024-07-11 16:19:57] Startup - Steam Client launched with: ['/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam'](steam://openurl_external/https://steamcommunity.com/linkfilter/?u=http%3A%2F%2F%27%2Fhome%2Fuser%2F.var%2Fapp%2Fcom.valvesoftware.Steam%2F.local%2Fshare%2FSteam%2Fubuntu12_32%2Fsteam%27) '-srt-logger-opened' '-no-cef-sandbox'
07/11 16:19:57 minidumps folder is set to /tmp/dumps
07/11 16:19:57 Init: Installing breakpad exception handler for appid(steam)/version(1718904662)/tid(135)
[2024-07-11 16:19:57] Loading cached metrics from disk [(/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/package/steam_client_metrics.bin)](steam://openurl_external/https://steamcommunity.com/linkfilter/?u=http%3A%2F%2F%28%2Fhome%2Fuser%2F.var%2Fapp%2Fcom.valvesoftware.Steam%2F.local%2Fshare%2FSteam%2Fpackage%2Fsteam_client_metrics.bin%29)
[2024-07-11 16:19:57] Using the following download hosts for Public, Realm steamglobal
[2024-07-11 16:19:57] 1. [https://client-update.akamai.steamstatic.com](steam://openurl/https://client-update.akamai.steamstatic.com), /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-07-11 16:19:57] 2. [https://cdn.cloudflare.steamstatic.com](steam://openurl/https://cdn.cloudflare.steamstatic.com), /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-07-11 16:19:57] 3. [https://cdn.steamstatic.com](steam://openurl/https://cdn.steamstatic.com), /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-07-11 16:19:57] Verifying installation...
[2024-07-11 16:19:58] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: [/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs](steam://openurl_external/https://steamcommunity.com/linkfilter/?u=http%3A%2F%2Fhome%2Fuser%2F.var%2Fapp%2Fcom.valvesoftware.Steam%2F.local%2Fshare%2FSteam%2Flogs)

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xed0058f0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xed0041c0
CAppInfoCacheReadFromDiskThread took 71 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 247
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam

![image](https://github.com/user-attachments/assets/3d7d1658-dbb6-4f80-a5a2-adb26fc95d85)

OS: Ubuntu

before about 1 year all were fine

Have anyone same issue, or know how to fix it?

**Comment by muXxer** [comment] 2024-07-12 08:22
Thanks, I just wanted to open exactly the same issue, and I was wondering why no one encountered it already.
For me it was working fine 2 days ago, then I made some updates including kernel and nvidia drivers, and then it stopped working.

If I look into the logs under `.var/app/com.valvesoftware.Steam/.local/share/Steam/logs/webhelper-linux.txt` I can see the following issue. 

Log:
```
steamwebhelper.sh[3518]: Using supervisor /home/USER/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[3518]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/USER/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[3518]: CEF sandbox already disabled
steamwebhelper.sh[3518]: Starting steamwebhelper with Sniper steam runtime at /home/USER/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.535.183.01 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/home/USER/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32:/home/USER/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/panorama:/app/lib/i386-linux-gnu/GL/default/lib:/app/lib/i386-linux-gnu/GL/nvidia-535-183-01/lib:/app/lib32:/app/lib/i386-linux-gnu:/lib64:/app/lib:/usr/lib/x86_64-linux-gnu/GL/default/lib:/usr/lib/x86_64-linux-gnu/GL/nvidia-535-183-01/lib:/usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/lib:/usr/lib/x86_64-linux-gnu/openh264/extra:/usr/lib/x86_64-linux-gnu", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
pressure-vessel-wrap[3537]: E: linkat: Datei oder Verzeichnis nicht gefunden
```

Important part:
```
Dependencies of libnvidia-pkcs11.so.535.183.01 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1"
```

It seems that a library is missing in the flatpak, that is used by the latest nvidia driver? Just my guess.

**Comment by Vennnot** [comment] 2024-07-12 08:27
Same here. Worked fine yesterday. Only thing I've done since then is `flatpak update`


Ubuntu 24.04 LTS
Radeon CPU and GPU

**Comment by webxon** [comment] 2024-07-12 08:40
> Thanks, I just wanted to open exactly the same issue, and I was wondering why no one encountered it already. For me it was working fine 2 days ago, then I made some updates including kernel and nvidia drivers, and then it stopped working.
Thanks for response too

> Important part:
> 
> ```
> Dependencies of libnvidia-pkcs11.so.535.183.01 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1"
> ```
> 
> It seems that a library is missing in the flatpak, that is used by the latest nvidia driver? Just my guess.
Its maybe really missed some X11 library in flatpak Steam repo, but I am on AMD GPU and CPU, so its not problem in Nvidia driver

**Comment by muXxer** [comment] 2024-07-12 08:41
> Radeon CPU and GPU
Ah so it's not only nvidia related :D

But I still guess it's because `libssl-dev` is missing, which should ship the `libcrypto.so` ? 
What does your logs say under `/home/USER/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs/webhelper-linux.txt` ?

**Comment by webxon** [comment] 2024-07-12 08:55
> > Radeon CPU and GPU
> 
> Ah so it's not only nvidia related :D
> 
> But I still guess it's because `libssl-dev` is missing, which should ship the `libcrypto.so` ? What does your logs say under `/home/USER/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs/webhelper-linux.txt` ?

If you will startup workable Steam with console feature you will be surprised how many erros its throwing, but working. But this time its not working)

**Comment by Vennnot** [comment] 2024-07-12 09:10
srt-logger[24324]: Log opened 2024-07-12 11:09:40+0200
steamwebhelper.sh[24319]: Using supervisor /home/daniel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[24319]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/daniel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[24319]: CEF sandbox already disabled
steamwebhelper.sh[24319]: Starting steamwebhelper with Sniper steam runtime at /home/daniel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
pressure-vessel-wrap[24338]: E: linkat: No such file or directory

Anyone know how long does it take for these issues to be fixed. I was planning on having a nice relaxing weekend gaming.

**Comment by webxon** [comment] 2024-07-12 09:14
> srt-logger[24324]: Log opened 2024-07-12 11:09:40+0200 steamwebhelper.sh[24319]: Using supervisor /home/daniel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor steamwebhelper.sh[24319]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/daniel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh steamwebhelper.sh[24319]: CEF sandbox already disabled steamwebhelper.sh[24319]: Starting steamwebhelper with Sniper steam runtime at /home/daniel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point pressure-vessel-wrap[24338]: E: linkat: No such file or directory
> 
> Anyone know how long does it take for these issues to be fixed. I was planning on having a nice relaxing weekend gaming.

Idk. But I now temporary using native Steam for Linux, and its works

**Comment by hrtkpf** [comment] 2024-07-12 10:26
Having the same issue since yesterday.

Workarounds are to either use the native Steam client or to downgrade Steam client and keep using the flatpak version (see https://github.com/ValveSoftware/steam-for-linux/issues/11006#issuecomment-2196024433).

I am using NVIDIA drivers 550.90.07

**Comment by predator5047** [comment] 2024-07-12 16:57
I also have the same issue on Ubuntu 24.04,  6.8.0-38-generic, with nvidia driver  550.90.07 on a RTX 3080
Using the workaround from the above comment allows steam to start

**Comment by seidelh** [comment] 2024-07-12 17:28
I also have the same issue. Steam was working fine yesterday until today. Ubuntu 24.04, 6.8.0-38-generic, ryzen 2700x, rx 5700.

**Comment by webxon** [comment] 2024-07-12 23:29
Its temporaly thing how to repaire Steam flatpak:
- open terminal
- use command: 
```shell
flatpak run com.valvesoftware.Steam -forcesteamupdate -forcepackagedownload -overridepackageurl  https://web.archive.org/web/20240210115543if_/http://media.steampowered.com/client -exitsteam
```

**Comment by DisasterIncarnate** [comment] 2024-07-13 04:04
reporting same issue from same time, roughly 2 days ago, as someone else mentioned its nothing nvidia related as i also have an amd gpu and cpu setup, tried all the usual reported methods and it still gives the steamwebhelper error on launch, uninstalled the whole thing and reinstalled with same error.

the log files in my case show nothing as they arent generated before it all hangs/crashes.

The only useful output i do get when launching via terminal is this output:
> src/steamUI/steamuisharedjscontroller.cpp (619) : Failed creating offscreen shared JS context

nothing else in my terminal output really stands out as a possible error, Webcxon's solution is working for me so far but would be nice to know whats gone wrong and how to fix.

**Comment by g2p** [comment] 2024-07-13 07:28
Here's what the linkat error looks like under strace:

    flatpak run --devel --env=LC_ALL=C --command=strace com.valvesoftware.Steam//beta -f -s 1024 -o strace -- steam


In another terminal, run

    tail -F ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs/*.txt

and look for the pressure-vessel pid in an error that looks like:

    pressure-vessel-wrap[176]: E: linkat: No such file or directory

Inside `~/.var/app/com.valvesoftware.Steam/strace` I have:
```
176   openat(AT_FDCWD, "…/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-O9I2Q2", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 8
…
176   openat(8, "usr/etc", O_WRONLY|O_CLOEXEC|O_TMPFILE, 0600) = 10
176   fchmod(10, 0600)                  = 0
176   fallocate(10, 0, 0, 64)           = 0
176   write(10, "pcm.!default {\n    type pulse\n}\nctl.!default {\n    type pulse\n}\n", 64) = 64
176   fchmod(10, 0644)                  = 0
…
176   linkat(AT_FDCWD, "/proc/self/fd/10", 8, "usr/etc/tmp.xwx1yI", AT_SYMLINK_FOLLOW) = -1 ENOENT (No such file or directory)
176   close(10)                         = 0
```

**Comment by g2p** [comment] 2024-07-13 08:21
@smcv Any idea what might have changed recently?  Something in a steam runtime?

**Comment by DisasterIncarnate** [comment] 2024-07-13 08:24
> Here's what the linkat error looks like under strace:
> 
> ```
> flatpak run --devel --env=LC_ALL=C --command=strace com.valvesoftware.Steam//beta -f -s 1024 -o strace -- steam
> ```
> 
> In another terminal, run
> 
> ```
> tail -F ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs/*.txt
> ```
> 
> and look for the pressure-vessel pid in an error that looks like:
> 
> ```
> pressure-vessel-wrap[176]: E: linkat: No such file or directory
> ```
> 
> Inside `~/.var/app/com.valvesoftware.Steam/strace` I have:
> 
> ```
> 176   openat(AT_FDCWD, "…/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-O9I2Q2", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 8
> …
> 176   openat(8, "usr/etc", O_WRONLY|O_CLOEXEC|O_TMPFILE, 0600) = 10
> 176   fchmod(10, 0600)                  = 0
> 176   fallocate(10, 0, 0, 64)           = 0
> 176   write(10, "pcm.!default {\n    type pulse\n}\nctl.!default {\n    type pulse\n}\n", 64) = 64
> 176   fchmod(10, 0644)                  = 0
> …
> 176   linkat(AT_FDCWD, "/proc/self/fd/10", 8, "usr/etc/tmp.xwx1yI", AT_SYMLINK_FOLLOW) = -1 ENOENT (No such file or directory)
> 176   close(10)                         = 0
> ```
> 
> Using intel graphics by the way. Thinking the screen recording beta might have broken things, but -clearbeta didn't help.

when i launch via terminal my steam briefly lock up at that pressurevessel output you mentioned then after a delay everything fails and all output after is about dump files, i get this which is slightly different to yours.

```
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
src/steamUI/steamuisharedjscontroller.cpp (619) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (619) : Failed creating offscreen shared JS context
07/13 09:21:24 Init: Installing breakpad exception handler for appid(steam)/version(1718904662)/tid(135)

```

**Comment by RichardJECooke** [comment] 2024-07-13 16:05
If I need to switch from Flatpak Steam to native Steam, how do I not lose all my settings, games, and my game's settings and saves please?

**Comment by g2p** [comment] 2024-07-13 16:08
> If I need to switch from Flatpak Steam to native Steam, how do I not lose all my settings, games, and my game's settings and saves please?

Something like this:

    mkdir ~/.steam
    ln -Ts ~/.var/app/com.valvesoftware.Steam/.local/share/Steam ~/.steam/steam
    ln -Ts ~/.var/app/com.valvesoftware.Steam/.local/share/Steam ~/.steam/root

**Comment by lothor** [comment] 2024-07-14 10:01
...
> Inside `~/.var/app/com.valvesoftware.Steam/strace` I have:
> 
> ```
> 176   openat(AT_FDCWD, "…/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-O9I2Q2", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 8
> …
> 176   openat(8, "usr/etc", O_WRONLY|O_CLOEXEC|O_TMPFILE, 0600) = 10
> 176   fchmod(10, 0600)                  = 0
> 176   fallocate(10, 0, 0, 64)           = 0
> 176   write(10, "pcm.!default {\n    type pulse\n}\nctl.!default {\n    type pulse\n}\n", 64) = 64
> 176   fchmod(10, 0644)                  = 0
> …
> 176   linkat(AT_FDCWD, "/proc/self/fd/10", 8, "usr/etc/tmp.xwx1yI", AT_SYMLINK_FOLLOW) = -1 ENOENT (No such file or directory)
> 176   close(10)                         = 0
> ```

Inspired by this strace output I've spent some time looking into why creation of the symbolic link is failing.

The linkat-error seems to be caused by the [recent apparmor-upgrade](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2064672) in Ubuntu 24.04.

An additional bwrap-profile was added in the new version. After hitting the "E: linkat: ..."-error the following log-messages have been generated by the kernel (journalctl -k):

    kernel: audit: type=1400 audit(1720947696.498:1840099): apparmor="DENIED" operation="link" class="file" info="Failed name lookup - deleted entry" error=-2 profile="bwrap" name="<HOME>/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-CWG3Q2/usr/etc/#10624521" pid=9421 comm="pressure-vessel" requested_mask="l" denied_mask="l" fsuid=<UID> ouid=<UID>
    kernel: audit: type=1400 audit(1720947696.498:1840100): apparmor="DENIED" operation="link" class="file" profile="bwrap" name="<HOME>/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-CWG3Q2/usr/etc/tmp.FgCzMU" pid=9421 comm="pressure-vessel" requested_mask="l" denied_mask="l" fsuid=1000 ouid=1000 target="<HOME>/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-CWG3Q2/usr/etc/#10624521"
    kernel: audit: type=1400 audit(1720947696.498:1840101): apparmor="DENIED" operation="link" class="file" info="Failed name lookup - deleted entry" error=-2 profile="unpriv_bwrap" name="<HOME>/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-CWG3Q2/usr/etc/#10624521" pid=9421 comm="pressure-vessel" requested_mask="l" denied_mask="l" fsuid=<UID> ouid=<UID>
    kernel: audit: type=1400 audit(1720947696.498:1840102): apparmor="DENIED" operation="link" class="file" profile="unpriv_bwrap" name="<HOME>/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-CWG3Q2/usr/etc/tmp.FgCzMU" pid=9421 comm="pressure-vessel" requested_mask="l" denied_mask="l" fsuid=<UID> ouid=<UID> target="<HOME>/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-CWG3Q2/usr/etc/#10624521"

## Workaround

Since I don't speak apparmor all that well I ended up removing said profile and restarting the computer to make sure the change is picked up:

    sudo rm /etc/apparmor.d/bwrap-userns-restrict
    sudo shutdown -r now

## Fix?

Someone slightly more security-concious should probably look into how to modify the bwrap-profile :)

**Comment by g2p** [comment] 2024-07-14 10:14
Thank you @lothor for finding the cause!

I can confirm that

    sudo aa-disable /etc/apparmor.d/bwrap-userns-restrict
    
Allows Flatpak Steam to work again.

**Comment by g2p** [comment] 2024-07-14 10:37
Reported here in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2072811

**Comment by kavishan59** [comment] 2024-07-14 14:14
aa-disable doesn´t work on my ubuntu 24.04 for some reason.

You can use this to disable it instead : 

```
sudo ln -s /etc/apparmor.d/bwrap-userns-restrict /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/bwrap-userns-restrict
```

If you want to re-enable it:

```
sudo rm /etc/apparmor.d/disable/bwrap-userns-restrict
cat /etc/apparmor.d/bwrap-userns-restrict | sudo apparmor_parser -a
```

I got the instructions from : https://ubuntu.com/server/docs/apparmor

**Comment by smcv** [comment] 2024-07-15 13:31
Please could someone with appropriate permissions retitle this to mention Ubuntu in its title, or close it as "not our bug"?

It looks as though this is a regression caused by an Ubuntu stable update (SRU), and is not anything that can be solved by Flatpak or by this particular app. https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2072811 is the place to look for a solution.

**Comment by sketchbuch** [comment] 2024-07-16 17:20
@webxon 's solution worked for me.

**Comment by webxon** [comment] 2024-07-16 17:48
> Please could someone with appropriate permissions retitle this to mention Ubuntu in its title, or close it as "not our bug"?
> 
> It looks as though this is a regression caused by an Ubuntu stable update (SRU), and is not anything that can be solved by Flatpak or by this particular app. https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2072811 is the place to look for a solution.

Hi, there! Yes! Confirm, its Ubuntu issue. I just remember that day, and I am 100% remeber that there are in upgrade list were apparmor application. So its 99% apparmor upgrade. (I will rename ticket)

I can confirm next solution for Ubuntu:

command
`sudo aa-disable /etc/apparmor.d/bwrap-userns-restrict`
was not working for me after input to console, I had 2 issues:
- issue 1) I have not installed on my Ubuntu copy apparmor utils, to fix it:
`sudo apt-get install apparmor-utils`
than (if you dont have apparmor configs installation, see my issue 2)
`sudo aa-disable /etc/apparmor.d/bwrap-userns-restrict`

- issue 2) I had 2 firefox installations (snap and downloaded package, so I just removed apparmor config for snap, because I just did not using it)

thats all, now I can restart my PC and I dont need to rewrite commands again after restarts.

If somebody have used my solution what I have been wrote before, you need now to upgrade Steam to latest version, you dont need anymore version from february, fix:
- Shutdown Steam client
- go to /home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/
- find config what to have created "Steam.cfg" and delate it
- Startup Steam client (february version), than click in top menu "Steam" > "Check for Steam Client Updates..."
- Wait until Steam client will be updated. Thats all. Now Steam flatpak client should be working without issue.

p.s. remember, if in future apparmor will be upgraded by Ubuntu Devs, this issue may be back, and you'll should repeat this steaps until this apparmor' issue will be fixed

**Comment by hrtkpf** [comment] 2024-07-16 21:53
FYI, the fix has now been released to the Ubuntu repos as part of the apparmor package. Just `apt update && apt upgrade && reboot` and the issue should be fixed.

I think this issue can be closed now.

**Comment by Smith6612** [comment] 2024-07-17 04:20
I can confirm the fix for Ubuntu 24.04 has been published to the Repos, and after installation, Steam is now able to work properly. On my system, I needed to run a `sudo apt install --only-upgrade apparmor file-roller libapparmor1` followed by a reboot, as the update was held back / deferred.

**Closed** 2024-07-17 06:30 UTC

**Comment by shymega** [comment] 2024-09-19 14:40
I get this on NixOS with the latest Flatpak. Will open another bug report, but I just thought I'd mention it.

**Comment by smcv** [comment] 2024-09-19 16:43
> I get this on NixOS

I'm pretty sure you don't get this issue, which was Ubuntu-specific and caused by AppArmor. Instead, I think you are getting the same symptom for a different reason.

Unfortunately, there are lots of reasons why `steamwebhelper` might not work, and they all look superficially the same.

**Comment by shymega** [comment] 2024-09-19 16:53
OK - apologies for bringing it up here.
