### ISSUE TITLE
Proton games don't start anymore in GNOME Wayland

### ISSUE THREAD

**Issue by nilsoffermann** [flathub/com.valvesoftware.Steam#578] opened 2020-06-21 22:02 UTC
**Game information**
Everything using Proton I think but I only specifically tested No Man's Sky and Subnautica.

**Distribution name and version where applicable**
Debian bullseye/sid

**Flatpak info**
Flatpak 1.6.3
default
host

**Problem description**
Whenever I start a game using Proton inside a GNOME Wayland session I either get a transparent game window or a black screen. It works fine with either Flatpak Steam/Xorg or native Steam/Wayland. I haven't changed any Flatpak permissions and non Proton games work fine. When I start the Steam Flatpak from the command line and try to start a Proton game it throws the following error: https://pastebin.com/04udEdyV

**Does this issue reproduce with native Steam**
No, the games work fine there

**Comment by rcrd8** [comment] 2020-06-22 09:06
I've also experienced that issue. I can say that it was something related to mesa in my case, as when using normal mesa 20.1 drivers games are working fine in Wayland, but when I tried to use mesa-git there was the same problem with transparent/black screen in Wayland. X11 worked fine, native steam worked fine for both X11 and Wayland.

**Comment by nilsoffermann** [comment] 2020-06-22 22:48
Yeah that would makes sense as Debian testing recently upgraded to mesa 20.1.1. So how would I be able to fix this? Just by waiting for an update to the Flatpak runtime?

**Comment by BrainBlasted** [comment] 2020-07-01 18:51
Also getting this on Fedora 32.

**Comment by ShinyRice** [comment] 2020-07-06 15:06
I'm getting this too on Sway 1.4, Void Linux, Flatpak 1.6.3. Haven't tested native Steam, nor on X. I mostly get black screens too, but I've gotten one or two white screens.

**Comment by BrainBlasted** [comment] 2020-07-07 20:57
@nanonyme Mesa [was updated to 20.1.2](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2796) in the Freedesktop SDK master branch. Do you think it would be viable to ship in 19.08?

**Comment by nanonyme** [comment] 2020-07-07 21:08
@valentindavid is going to do release tag as soon as GnuTLS backport is done. Note that it's now also possible to try 20.08beta with beta branch of this app. This will have the new Mesa.

**Comment by BrainBlasted** [comment] 2020-07-07 21:10
Can verify that the 20.08beta works on Wayland, just tried it out.

**Comment by valentindavid** [comment] 2020-07-08 11:28
I just tested No Man's Sky on GNOME OS master with GNOME on Wayland. Proton 5.0. Both com.valvesoftware//stable and com.valvesoftware//beta (with respectively 19.08.11 and 20.08beta.2).

I can confirm 19.08 has a black screen and hangs. 20.08beta works (I only tested the menu since I am working).

I will try to make a local build 19.08 with newer Mesa.

**Comment by nanonyme** [comment] 2020-07-08 12:59
19.08 already has Mesa backported, just needs release tag?

**Comment by valentindavid** [comment] 2020-07-08 14:12
Same issue with  Mesa 20.1.2 on 19.08. Is the vkd3d on com.valvesoftware.Steam//stable the issue?

**Comment by valentindavid** [comment] 2020-07-08 14:12
Ah actually, it works after a while. Just it does not show the logos on start.

**Comment by valentindavid** [comment] 2020-07-08 14:20
It goes black when changing window. It comes back after doing alt+tab multiple times.

There is a difference between the versions of Mesa. So it is at least partially fixed. But there is another bug.

Once the gnutls fix is merged I will make a new release tag.

**Comment by valentindavid** [comment] 2020-07-11 11:28
Freedesktop SDK 19.08.12 has been released. And now `com.valvesoftware.Steam//stable` can run "No Man's Sky" on GNOME Wayland for me.

Consider closing this issue.

**Closed** 2020-07-11 13:06 UTC
