### ISSUE TITLE
I can not create desktop shortcut

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#174] opened 2018-08-25 13:48 UTC
I can not create game shortcuts on the desktop because Endless OS only allows Flatpak applications to be attached. Would it be possible to generate a Flatpak shortcut? to be able to fix games on the desktop in Endless OS.

**Comment by nanonyme** [comment] 2018-08-25 13:53
Seems essentially like a duplicate of #85
We're exposing Steam desktop file already, I don't think there is much more we can do

**Closed** 2018-08-25 14:09 UTC
