### ISSUE TITLE
 OpenSuse tumbleweed libc.so.6

### ISSUE THREAD

**Issue by luisXoliveira** [flathub/com.valvesoftware.Steam#303] opened 2019-01-08 17:51 UTC
**Game information**
 
steam doesn't open

**Distribution name and version where applicable**
 
Opensuse

**Flatpak info**

Flatpak 1.0.6
default
host

**Problem description**

when i try to launch the steam he not open and display message informing missing libc.so.6

**Does this issue reproduce with native Steam**
no

**Comment by Alexander-Wilms** [comment] 2019-01-08 18:09
Duplicate of #1?

**Comment by nanonyme** [comment] 2019-01-08 18:13
Which GPU is this with?

**Comment by nanonyme** [comment] 2019-01-11 07:43
Also this is 64bit host, right?

**Comment by nanonyme** [comment] 2019-03-29 21:00
Closing as no input.

**Closed by nanonyme** 2019-03-29 21:00 UTC
