### ISSUE TITLE
Steam overlay does not works in Vulkan API games

### ISSUE THREAD

**Issue by Shished** [flathub/com.valvesoftware.Steam#145] opened 2018-08-20 09:40 UTC
When any game that uses Vulkan API is launched from Steam, it does not shows FPS counter and shift-tab does not opens Steam overlay.
Same game will show overlay if launched in openGL mode.

Non-flatpak Steam installation has no such problem.
Terminal output does not shows anything relevant.

CPU: intel core i5-3570k
GPU: GTX 660 with proprietary driver v.396.51
OS: openSUSE Tumbleweed with Linux 4.17.14
Flatpak 0.11.8.3
org.freedesktop.Platform 18.08

**Comment by nanonyme** [comment] 2018-08-20 14:08
Has this worked before? Any suggested reproducer games?

**Comment by Shished** [comment] 2018-08-20 19:18
> Has this worked before?

I don't know.

> Any suggested reproducer games?

Dota 2 (with vulkan support DLC), any new Unity-based game with "-force-vulkan" parameter, The Talos Principle, Serious Sam Fusion games, Mad Max, RotTR.

**Comment by LeandroStanger** [comment] 2018-08-21 14:06
@Shished Upgrade Flatpak to version 1.0

**Comment by Shished** [comment] 2018-08-21 14:14
I will and then will report.

**Comment by valentindavid** [comment] 2018-08-21 20:02
It looks for file in `/home/<user>/.var/app/com.valvesoftware.Steam/data/vulkan/implicit_layer.d`. But files are in  `/home/<user>/.local/share/vulkan/implicit_layer.d`. This probably due to migration issues. Please test again when  #150 is merged.

**Comment by nanonyme** [comment] 2018-08-21 21:01
Can you please retry now?

**Comment by Shished** [comment] 2018-08-22 05:28
com.valvesoftware.Steam was updated to cee6aa772a02.
It works now in all tested games.

**Closed** 2018-08-22 05:28 UTC
Labels: bug
