### ISSUE TITLE
Missing Tray Icon

### ISSUE THREAD

**Issue by MichaelAquilina** [flathub/com.valvesoftware.Steam#23] opened 2017-07-23 17:43 UTC
`Linux linux-vtrr 4.11.8-1-default #1 SMP PREEMPT Thu Jun 29 14:37:33 UTC 2017 (42bd7a0) x86_64 x86_64 x86_64 GNU/Linux`

OpenSUSE Tumbleweed

![screenshot from 2017-07-23 18-43-30](https://user-images.githubusercontent.com/2650040/28501585-c4324d0a-6fd6-11e7-8b2c-d1697604a34b.png)

Let me know if there is any information I can I get which will help debug this.

**Comment by Francesco149** [comment] 2017-07-23 19:15
duplicate of #4 

seems like it's something wrong with the GtkStatusIcon fallback

**Closed** 2017-07-23 20:58 UTC

**Comment by MichaelAquilina** [comment] 2017-07-23 21:16
Thanks :)
