### ISSUE TITLE
Steam tray icon is empty when using (K)StatusNotifierItem/AppIndicator Support extension

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.valvesoftware.Steam#322] opened 2019-02-23 15:48 UTC
**Distribution name and version where applicable**
NAME=Fedora
VERSION="29.20190223.0 (Workstation Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29.20190223.0 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
OSTREE_VERSION=29.20190223.0

**Flatpak info**
Flatpak 1.2.3

**Problem description**
The Steam tray icon seems to be empty when using the [(K)StatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) GNOME Shell extension from Canonical. Other applications don't have this issue. See this screenshot:

![Steam tray menu](https://user-images.githubusercontent.com/2339930/53288602-70438b00-378a-11e9-8892-9fdb2bbca201.png)

**Does this issue reproduce with native Steam**
Have not tested

**Comment by nanonyme** [comment] 2019-02-25 21:30
Has this worked before?

**Comment by danrobinson78** [comment] 2019-03-12 12:43
For what it's worth I'm seeing the same behavior under Plasma as well. Also on Fedora 29.

**Comment by danrobinson78** [comment] 2019-03-13 00:24
Per a comment on Reddit, I was able to symlink ~/.var/app/com.valvesoftware.Steam/.local/share/Steam to ~/.local/share/Steam and it caused the icon to appear.

**Comment by nanonyme** [comment] 2019-03-13 07:27
Hmm, sounds like it's that path fixup that caused this as a side-effect then. You can force Steam to recalculate paths by renaming .var/app com.valvesoftware.Steam/.steam iirc

**Comment by nanonyme** [comment] 2019-03-13 07:29
Basically the issue was having .var/app com.valvesoftware.Steam in XDG paths resulted in overlong paths for Proton and caused random failures depending on username and game name length

**Comment by maxtorete** [comment] 2019-05-04 00:59
I renamed .var/app/com.valvesoftware.Steam/.steam but it doesn't work, I have to symlink ~/.var/app/com.valvesoftware.Steam/.local/share/Steam to ~/.local/share/Steam

It was working before in my previous Fedora 29 installation, but in the clean installed Fedora 30 the icon was empty.

**Comment by jdtanner** [comment] 2019-05-08 22:28
Same issue here with Ubuntu 19.04 and Steam Flatpak :(

**Comment by johnr14** [comment] 2019-06-19 03:46
On Fedora 30 clean install, got same empty icon, fixed with 
`ln -s ~/.var/app/com.valvesoftware.Steam/.local/share/Steam  ~/.local/share/Steam`

Could the flatpak be updated to fix this small thing ? Thanks

**Comment by nanonyme** [comment] 2019-06-19 05:33
That's a workaround and no. The app cannot write to random locations in your home on purpose.

**Comment by johnr14** [comment] 2019-06-19 06:33
Is the icon fetched by KDE/Gnome or supplied by Steam to the systray ?
Would the fix need to be from KDE/Gnome/Distribution team ?

@nanonyme  effectively, com.valvesoftware.Steam doesn't have access to home, so it should not be able to load the icon even with the symlink. Then it should be loaded by the system tray process.

Could there be a PATH export of $XDG_DATA_DIRS that could fix this ? 

Could perhaps the file /etc/profile.d/flatpak.sh be updated to fix the path problem for system icons ?

**Comment by nanonyme** [comment] 2019-06-19 09:23
Hmm. I may know the root cause. If Steam tells the external software path for icon, that would be incorrect one since Steam works inside sandbox prefix that it is not aware of (due to sandbox). This isn't really straightforward to fix.

**Comment by nanonyme** [comment] 2019-06-19 09:32
If some library is used, it might be possible to patch and replace, at least after update to runtime version 19.08.

**Comment by nanonyme** [comment] 2019-07-12 20:38
I'm actually starting to wonder if we did the sandboxing wrong and if .local/share/Steam should be a hole in the sandbox. I'm not at all sure whether we can in any sensible way to overcome to migrate at this point anymore. @TingPing any insight?

**Comment by iavael** [comment] 2019-08-03 02:04
Dirty hotfix to adjust symlinks in ~/.var/app/com.valvesoftware.Steam/.steam instead of creaing symlink in host system at path ~/.local/share/Steam
```bash
for i in $(ls ~/.var/app/com.valvesoftware.Steam/.steam); do
  LINK="~/.var/app/com.valvesoftware.Steam/.steam/$i"
  test -L $LINK && {
    OLDTGT="$(readlink \"$LINK\")"
    grep -qFi .local/share/Steam <<<"$OLDTGT" && {
      NEWTGT=$(sed "s|$HOME/.local/share/|$HOME/.var/app/com.valvesoftware.Steam/.local/share/|g" <<<"$OLDTGT")
      rm -f $LINK && ln -s $NEWTARGET $LINK
    }
  }
done
```

**Comment by nightuser** [comment] 2020-01-28 08:19
I wonder why flatpak or steam replaces relative symlinks from .steam folder to .local/share to absolute paths (and they become incorrect since they are changed to user's home folder instead of correct path in .var).

**Comment by nanonyme** [comment] 2020-01-28 08:37
Steam creates the symlinks and they resolve just fine inside the sandbox. The problem is this icon resolution happens outside sandbox.

**Comment by nightuser** [comment] 2020-01-28 08:52
@nanonyme I meant that steam creates symlinks with absolute paths instead of relative (`ln -s ../.local/share/Steam .steam/steam`)

**Comment by nanonyme** [comment] 2020-01-28 08:54
Well, it has to. Those point to whereever XDG_DATA_HOME and friends point to. The targets are allowed to even be outside your home directory.

**Comment by nightuser** [comment] 2020-01-28 09:14
@nanonyme Yeah, makes sense. Then [this comment](https://github.com/flathub/com.valvesoftware.Steam/issues/322#issuecomment-472232047) is still the cleanest solution but still ugly.

I wonder how many applications still use `~/.steam` instead of the XDG one (it's there for legacy reasons).

**Comment by nanonyme** [comment] 2020-01-28 12:28
Well, ideally we would probably intercept the API calls and mangle paths before letting host see them. This thing is kind of an implementation detail of the sandbox. I don't know exactly how this communication with the host works though.

**Comment by AsciiWolf** [comment] 2020-02-18 09:50
Not sure what changed, but Flatpak Steam tray icon now seems to be displayed without any issue on my Fedora 31 Workstation (Wayland) system with latest `gnome-shell-extension-appindicator` package installed from the system repository.

**Comment by wyphan** [comment] 2020-04-18 23:17
Same issue here, on Ubuntu 18.04.4 with Flatpak 1.0.9 from the default Ubuntu repos. Here's the weird part: the suggested fix from [this comment](https://github.com/flathub/com.valvesoftware.Steam/issues/322#issuecomment-517885819) doesn't work for me, but [this one](https://github.com/flathub/com.valvesoftware.Steam/issues/322#issuecomment-472232047) works. As @nanonyme pointed out, this is a workaround that defeats the sandbox, but I guess I'll take it for now.

**Comment by iavael** [comment] 2020-04-19 00:25
@wyphan did you use generator or used already generated commands from comment? If you used generator, did you actually run generated hot fix?

**Comment by wyphan** [comment] 2020-04-19 02:35
@iavael Ah right, I used the generator but forgot to run the generated commands, my bad.

**Comment by alexmex90** [comment] 2020-05-06 07:21
![Screenshot from 2020-05-06 00-19-11](https://user-images.githubusercontent.com/43529725/81147608-7ce77580-8f2f-11ea-94a3-064531eebf2f.png)

I'm having the same issue here in Debian 10

**Comment by flukejones** [comment] 2020-09-01 22:10
> On Fedora 30 clean install, got same empty icon, fixed with @danrobinson78 answer
> `ln -s ~/.var/app/com.valvesoftware.Steam/.local/share/Steam ~/.local/share/Steam`
> 
> Could the flatpak be updated to fix this small thing ? Thanks

I need to bookmark this reply. Worked perfectly on fedora.

**Comment by wsdfhjxc** [comment] 2020-12-23 10:28
Revoking `talk-name=org.kde.StatusNotifierWatcher` permission also causes the icon to be displayed correctly.

**Comment by RafalSkolasinski** [comment] 2021-01-09 18:03
Still an issue. Creating symlink works.

@wsdfhjxc could you extend your reply to include the full command to execute?

**Comment by wsdfhjxc** [comment] 2021-01-10 14:28
@RafalSkolasinski  Okay, so the actual command is:

```
flatpak --user override com.valvesoftware.Steam --no-talk-name=org.kde.StatusNotifierWatcher
```

However, it causes the tray icon to be displayed in a different way than through the SNI. For example, the context menu doesn't pick up the system colors (talking about KDE Plasma). Depending on your needs, this may be acceptable for you, or not.

Either way, this is not a solution to the issue, but more like an observation that it has to do with the SNI.

**Comment by kaimast** [comment] 2021-01-12 00:39
I have a similar problem, but for some reason it shows three dots in my appmenu. See the second icon from the left below.

![image](https://user-images.githubusercontent.com/4525445/104254340-39d58e80-543c-11eb-9257-02515a7b565f.png)

(Screenshot is of GNOME with dash-to-panel, but happens with vanilla GNOME too)

**Comment by flukejones** [comment] 2021-01-12 00:42
@kaimast this will fix it: `ln -s ~/.var/app/com.valvesoftware.Steam/.local/share/Steam ~/.local/share/Steam`

**Comment by kaimast** [comment] 2021-01-12 00:44
> @kaimast this will fix it: `ln -s ~/.var/app/com.valvesoftware.Steam/.local/share/Steam ~/.local/share/Steam`

It does. Thanks a lot!

**Comment by nanonyme** [comment] 2021-02-24 20:58
I suggest removing that above symlink, updating to latest build and seeing if following instructions in https://github.com/flathub/com.valvesoftware.Steam/issues/480#issuecomment-779296054 help to fix the issue properly.

**Comment by gasinvein** [comment] 2021-02-25 08:43
@flukejones Please don't apply such hacks. We have hard time catching corner cases like this in the steam wrapper, it can break any time and at worst cause data loss.

**Comment by johnr14** [comment] 2021-02-25 11:40
@nanonyme I can confirm that on a fresh install, the system icon is shown by default on my Fedora 34 KDE. 
But, steam show no icons in KDE's launch menu.

**Comment by nanonyme** [comment] 2021-02-25 15:45
Did it show them previously?

**Closed** 2021-02-25 16:57 UTC

**Comment by johnr14** [comment] 2021-02-26 12:56
@nanonyme I tried a few times, and the icon will show if Steam is installed as  --user. But there is no icon if steam is installed as --system.
