### ISSUE TITLE
can't run because can't make symlink

### ISSUE THREAD

**Issue by andreasn** [flathub/com.valvesoftware.Steam#58] opened 2018-01-03 22:27 UTC
`flatpak run com.valvesoftware.Steam `
gives the error:
`bwrap: Can't make symlink at /home: File exists`

On Fedora Atomic Workstation 27.35

**Comment by TingPing** [comment] 2018-01-03 22:44
Duplicate of #57

**Closed by TingPing** 2018-01-03 22:44 UTC
