### ISSUE TITLE
steam-wrapper is trying to read a nonexistent file

### ISSUE THREAD

**Issue by jjedelsky** [flathub/com.valvesoftware.Steam#771] opened 2021-06-03 17:51 UTC
The steam-wrapper is crashing, because ~/.steam/root does not exist. As a result, launching Steam fails silently.

```sh
$ flatpak run com.valvesoftware.Steam
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.8/site-packages/steam_wrapper.py", line 362, in main
    current_xdg_prefix = get_current_xdg_dir_prefix()
  File "/app/lib/python3.8/site-packages/steam_wrapper.py", line 298, in get_current_xdg_dir_prefix
    current_steam_root = os.readlink(os.path.expanduser("~/.steam/root"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/home/myUserNameIsHere/.steam/root'
```

A workaround is to create the symlink manually: `ln -s ~/.local/share/Steam ~/.var/app/com.valvesoftware.Steam/.steam/root`.

**Comment by gasinvein** [comment] 2021-06-03 18:06
Duplicate of #763, although I wonder how the symlinks ends up missing.

**Comment by nanonyme** [comment] 2021-06-03 19:11
@gasinvein somehow it must be related to the crashes. There's also been a lot of crash reports lately.

**Closed** 2021-06-03 19:12 UTC

**Comment by gasinvein** [comment] 2021-06-03 19:16
Well, if `~/.steam` is there while`~/.steam/root` isn't, it means that Steam Client crashed on the first launch?

**Comment by nanonyme** [comment] 2021-06-03 19:18
Well, https://github.com/flathub/com.valvesoftware.Steam/issues/755 is specifically about that.
