### ISSUE TITLE
ONI, Steam, PulseAudio

### ISSUE THREAD

**Issue by BinaryAura** [flathub/com.valvesoftware.Steam#333] opened 2019-03-26 21:34 UTC
**Game information**
Oxygen Not Included

**Distribution name and version where applicable**
Fedora 29

**Flatpak info**
Flatpak 1.2.3
nvidia-418-43
default
host

**Problem description**
After installing steam through flathub.org, I attempted to install Oxygen Not Included (ONI). The game launches, but is unable to output any sound at all. I contacted Klei Entertainment about this. They said the game uses PulseAudio, but it seems that the game cannot access PulseAudio from flatpak's sandbox. Attached is the email correspondence between Klei Entertainment and myself. I installed Steam through flathub.org's repo and ONI via default install in Steam.

**Does this issue reproduce with native Steam**
Not tested

Correspondence with Klei Entertainment: 
[klei.pdf](https://github.com/flathub/com.valvesoftware.Steam/files/3010453/klei.pdf)

**Comment by nanonyme** [comment] 2019-03-26 23:28
Probably duplicate of https://github.com/flathub/com.valvesoftware.Steam/issues/325

**Comment by nanonyme** [comment] 2019-03-29 10:40
Please update and re-test

**Closed** 2019-04-04 12:31 UTC
