### ISSUE TITLE
Rise of the Tomb Raider is missing sound again

### ISSUE THREAD

**Issue by Tids** [flathub/com.valvesoftware.Steam#325] opened 2019-03-03 12:03 UTC
**Game information**
Rise of the Tomb Raider

**Distribution name and version where applicable**
```
lsb_release -a                    
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
**Flatpak info**
```
Flatpak 1.2.3
flatpak --gl-drivers                

default
host
```

**Problem description**
Since I can run that game now again, I was able to test this and there is no sound at all inside the game. Other games work just fine. The only sound related output I could catch when launching the game was:
```
ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_empty_open
ALSA lib ../../src/dlmisc.c:296:(snd1_dlobj_cache_get) symbol _snd_pcm_empty_open is not defined inside [builtin]
```
**Does this issue reproduce with native Steam**
Have not tested

**Comment by nanonyme** [comment] 2019-03-03 12:34
Could you double-check if they're shipping ALSA libraries inside the game directory?

**Comment by nanonyme** [comment] 2019-03-03 12:35
Original ticket #93 for audit trail

**Comment by nanonyme** [comment] 2019-03-03 12:37
Didn't you have some earlier ticket on this? I'm pretty sure I saw those symbols in an earlier ticket but can't find it.

**Comment by Tids** [comment] 2019-03-03 16:49
I think it was on Rocket League last time and was fixed by a freedesktop runtime update.

**Comment by nanonyme** [comment] 2019-03-03 16:54
No similar log outputs with that log.

**Comment by m0nt3sh0t** [comment] 2019-03-05 04:41
I can confirm same issue on OpenSuSe Tumbleweed 20190301 flatpak version 1.2.3

ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_empty_open
ALSA lib ../../src/dlmisc.c:296:(snd1_dlobj_cache_get) symbol _snd_pcm_empty_open is not defined inside [builtin]

Other tested games work.

**Comment by manuel-rhdt** [comment] 2019-03-14 13:47
I have the same issue with another game (Age of Wonders III). I am using Fedora 29. Seems like the game is using ALSA for audio playback.

I get the following error log messages when starting the game:

```
ALSA lib ../../src/dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol _snd_pcm_empty_open
ALSA lib ../../src/dlmisc.c:296:(snd1_dlobj_cache_get) symbol _snd_pcm_empty_open is not defined inside [builtin]
[SOUND] [WARNING] Error initializing output device.  FMOD: Could not initialize the FMOD system.[ERROR]Assertion failed: "false" 
Message: Failed to setup sound system 
```

**Comment by Pixelnarium** [comment] 2019-03-15 13:48
I have the same problem outside of Steam. Pretty sure it is a runtime issue. I created a bug report https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/694

**Comment by valentindavid** [comment] 2019-03-15 20:38
Thanks for reporting. This will be fixed in the next push. As a work around, you can create a file in `.var/app/com.valvesoftware.Steam/.asoundrc` with the following content:

```
pcm.!default {
    type pulse
    hint {
        show on
        description "Default ALSA Output (currently PulseAudio Sound Server)"
    }
}

ctl.!default {
    type pulse
}
```
```

**Comment by AlexRogaleski** [comment] 2019-03-24 22:10
> Obrigado por denunciar. Isso será corrigido no próximo push. Como solução, você pode criar um arquivo `.var/app/com.valvesoftware.Steam/.asoundrc`com o seguinte conteúdo:
> 
> ```
> pcm.!default {
>     type pulse
>     hint {
>         show on
>         description "Default ALSA Output (currently PulseAudio Sound Server)"
>     }
> }
> 
> ctl.!default {
>     type pulse
> }
> ```
> ```
> 
> ```

Worked, thank you!

**Comment by nanonyme** [comment] 2019-03-29 10:41
Please test again without workaround

**Comment by CisBetter** [comment] 2019-03-30 15:41
@nanonyme 
At least for me, running `rm .var/app/com.valvesoftware.Steam/.asoundrc` made the problem reappear.

Correct me if I'm wrong, but sadly, this issue's still not fixed.

**Comment by Pixelnarium** [comment] 2019-03-30 19:48
Did you run `flatpak update` before that?

**Comment by CisBetter** [comment] 2019-03-30 21:19
AFAIK my installation is (and was) up-to-date.
However, I first updated the Flatpak installation and then removed the file.
If the update added this file, this might have caused this problem again.

**Comment by nanonyme** [comment] 2019-04-02 07:31
You literally ran flatpak update without any additional parameters, right?

**Comment by Tids** [comment] 2019-04-02 17:47
For me it seems to be fixed on the machine with reverted workaround as well as on the other machine without the workaround. Both do now have sound in RotTR

**Comment by CisBetter** [comment] 2019-04-04 11:51
@nanonyme I just ran `flatpak update` updating all runtimes, apps, and locales.

However, after removing the file and then reinstalling steam using `flatpak install --reinstall com.valvesoftware.steam` sound seems to be fixed. Therefore, I think this issue could be closed.

**Closed** 2019-04-04 12:16 UTC
