### ISSUE TITLE
Can’t start if symlink in home direcory exists

### ISSUE THREAD

**Issue by jurf** [flathub/com.valvesoftware.Steam#66] opened 2018-02-25 12:07 UTC
I get this:

    bwrap: Can't make symlink at /home/jurf/Arch: File exists

**Comment by jurf** [comment] 2018-04-28 17:37
I renamed the thing to `Archlinux`. Now I get this:

```
❯ flatpak run com.valvesoftware.Steam 
bwrap: Can't make symlink at /home/jurf/Archlinux: File exists
```

**Comment by jurf** [comment] 2018-05-05 12:06
Turns out I can start Steam if I rename it before launching. I can rename it back right after.

**Comment by jurf** [comment] 2018-05-08 09:44
This is the `info -m` of Steam: https://pastebin.com/6rBP0S9n

As you can see it should only have access to `xdg-music`, but, somehow, it recreates symlinks found in the home directory.

```
~/.var/app/com.valvesoftware.Steam 
❯ cat /var/lib/flatpak/overrides/com.valvesoftware.Steam 
[Context]
filesystems=/data/games/steamapps;
```
```
~/.var/app/com.valvesoftware.Steam 
❯ ls
Archlinux@  cache/  config/  data/  Hudba@

~/.var/app/com.valvesoftware.Steam 
❯ file Archlinux 
Archlinux: broken symbolic link to ../../oldhome/home/juraj/

~/.var/app/com.valvesoftware.Steam 
❯ file ~/Archlinux
/home/jurf/Archlinux: symbolic link to /oldhome/home/juraj/
```

Passing `--nofilesystem=xdg-music` doesn’t do anything.

**Comment by alexlarsson** [comment] 2018-05-08 10:00
Can you `flatpak run -vv com.valvesoftware.Steam`? It should give us the full bwrap commandline.

**Comment by jurf** [comment] 2018-05-08 10:29
Here you go, let me know if I trimmed it incorrectly: https://pastebin.com/iFyYcMiY

**Comment by alexlarsson** [comment] 2018-05-08 12:25
Ok, so, here is what happens:

Due to your filesystem layout the `--filesystem=xdg-music` arguments leads flatpak to expose the symlink `$HOME/Archlinux` (because the music dir is a symlink into this symlink). At this point nothing "normal" has exposed the $HOME path in the sandbox, so flatpak thinks its unintialized and thus part of the root tmpfs, so it creates a symlink there. 

Unfortunately, this code ignores the `--bind $HOME/.var/app/com.valvesoftware.Steam/. $HOME/.` that is created by `--persist=.`, before any of the other exposes, so the symlink ends up at `$HOME/.var/app/com.valvesoftware.Steam/Archlinux` on the host instead, which fails with EEXIST the second time.

**Comment by alexlarsson** [comment] 2018-05-08 12:30
A simpler reproducer is probably something like:
```
ln -s /opt ~/symlink
flatpak run --filesystem=~/symlink --persist=. org.some.App
```

**Comment by alexlarsson** [comment] 2018-05-08 12:32
Yeah:
```
$ ln -s /opt ~/symlink
$ flatpak run --filesystem=~/symlink com.valvesoftware.Steam 
... exit it
flatpak run --filesystem=~/symlink com.valvesoftware.Steam 
bwrap: Can't make symlink at /home/alex/symlink: File exists
```

**Comment by i-need-to-tell-you-something** [comment] 2018-07-17 13:51
Any workaround or fix to this? I get the error from having my /home/me/Music as a symlink to a different disk (both with ext4 fs).

**Comment by nanonyme** [comment] 2018-07-17 15:12
There is the obvious one to not have symlinks. The actual fix is tracked in linked issue, probably

**Comment by i-need-to-tell-you-something** [comment] 2018-07-17 16:08
@nanonyme Thanks. Never underestimate people's capabilities to not realize obvious things. Also i guess i was hoping for something more simple. E.g. in my case my music and videos cant fit on my SSD (where the rest of my $HOME lies).
@jurf I would disagree with that as the solution since there is a lot of software that ignores XDG Base Directory Specification thus still needing an old fashioned link. Most games for example.

**Comment by jurf** [comment] 2018-07-17 16:34
@i-need-to-tell-you-something why would your games need access to your music? Also, ~/Music is a XDG standard directory, so it’s weird if an app is making use of it, but not honoring the XDG settings. In that case I think you can configure it elsewhere anyway.

**Comment by nanonyme** [comment] 2018-07-17 17:34
Having games access games is a perfectly plausible request imo. Some games can play user music as in-game music.

**Comment by jurf** [comment] 2018-07-17 17:57
We’re talking about Steam here however. Steam Music, the preffered way to play your music while playing games has a completely configurable directory. And games that directly need access to your library for gameplay definitely don’t have ~/Music hardcoded anyway.

And there’s nothing preventing you to make a ~/Music symlink, if you don’t set the symlink as the XDG directory.

**Comment by jurf** [comment] 2018-07-17 17:59
Also, yes, this is a bug, but it’s really hard to fix, and this is a perfectly viable workaround for the few edge cases for now.

**Comment by nanonyme** [comment] 2018-07-17 18:03
If the path indeed is configurable in this case, it's probably better to just directly expose the music filesystem mount point to the Flatpak application rather that fooling around with symlinks. That said, it's starting to sound to me like currently the --persist=. might be a bad call in Steam until related Flatpak about symlinks is resolved.

**Comment by nanonyme** [comment] 2018-07-17 18:06
The issue seems like a regression from d2f28baa369de63c28ea55524b94bd57708c8890

**Comment by nanonyme** [comment] 2018-08-16 15:26
Added entry to https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions, closing this since this is a Flatpak issue, not app issue

**Closed by nanonyme** 2018-08-16 15:26 UTC
