### ISSUE TITLE
Steam not launching anymore

### ISSUE THREAD

**Issue by anonymous98721515** [flathub/com.valvesoftware.Steam#281] opened 2018-12-22 13:21 UTC
Distribution name and version where applicable
Ubuntu 18.10

Flatpak info
Using "flatpak addon" in discovery store

Problem description
I succesfully had installed steam from flatpak and was using it without errors. But then one day it just stopped working :/ . Tried to reinstall and that kinda stuff, but nothing worked

Does this issue reproduce with native Steam

Native steam is fully working, but i really liked the contained version due to it being unable to detect my vpn ^^

**Comment by LeandroStanger** [comment] 2018-12-23 13:04
Update Steam
1) Open the application called 'Terminal'
2) In this application run the command:
>flatpak update --appstream && flatpak update

**Comment by vdrandom** [comment] 2018-12-23 20:54
Same here.
Updated both flatpak and com.valvesoftware.Steam on my archlinux, and boom.
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```
Steam runs perfectly natively, but I do still prefer to bubblewrap the proprietary applications.

**Comment by LeandroStanger** [comment] 2018-12-23 21:36
https://github.com/flathub/com.valvesoftware.Steam/pull/282

**Comment by LeandroStanger** [comment] 2018-12-26 22:16
Fixed in https://github.com/flathub/com.valvesoftware.Steam/pull/287

**Comment by nanonyme** [comment] 2018-12-26 22:16
The update is now merged through  #283  though I doubt it helps any here

**Comment by nanonyme** [comment] 2018-12-27 07:37
I doubt the update helps so would be nice to get further comments from original reporter

**Comment by nanonyme** [comment] 2018-12-27 07:42
Same errors as in https://github.com/ValveSoftware/steam-for-linux/issues/5859

**Comment by nanonyme** [comment] 2018-12-27 13:53
Please also post output of

flatpak run --command bash com.valvesoftware.Steam 

Followed by "locale"

**Comment by nanonyme** [comment] 2018-12-30 15:35
Assuming this still reproduces for you original reporters. Does it?

**Comment by nanonyme** [comment] 2019-02-19 20:26
Closing due to lack of comments.

**Closed by nanonyme** 2019-02-19 20:26 UTC
