### ISSUE TITLE
Crypt of the Necrodancer is way too fast / distorted sound

### ISSUE THREAD

**Issue by HaasJona** [flathub/com.valvesoftware.Steam#426] opened 2019-09-01 16:10 UTC
**Game information**
Crypt of the Necrodancer

**Distribution name and version where applicable**
Fedora 30 Workstation

**Flatpak info**
Flatpak 1.4.2
default
host

**Problem description**
When starting Crypt of the Necrodancer in Steam Flatpak the game runs way too fast and the music and other sounds are also played way to fast and sound almost like static. It's roughly about 20x as fast as it should.

**Does this issue reproduce with native Steam**
No, the same game runs absolutely fine on native Steam from rpmfusion.

**Comment by nanonyme** [comment] 2019-09-10 20:46
Could you please run "flatpak update" and test again? Runtime was just updated to 19.08.

**Comment by HaasJona** [comment] 2019-09-11 20:11
It's unchanged with 19.08 runtime, the game runs still way too fast.

**Comment by Lyle-Tafoya** [comment] 2019-09-26 10:35
I can confirm this issue. The game runs much faster than it's supposed to, resulting in distorted sounding audio as well as causing the level timer to run out within seconds. This issue cannot be reproduced with native Steam. If I had to guess, I'd say this is probably some kind of audio configuration issue and the gameplay being sped up is a side effect of how the game was designed to have player turns synced with the audio.

**Comment by nanonyme** [comment] 2019-09-26 10:40
@valentindavid any clue?

**Comment by HaasJona** [comment] 2019-09-26 11:02
I've found this reddit post which describes a similar issue: https://www.reddit.com/r/necrodancer/comments/4e8i6e/audio_and_visual_glitching_on_linux/?utm_source=amp&utm_medium=&utm_content=post_body

Apparently the problem can happen with a bad pulseaudio configuration. Maybe there's something wrong with how pulse audio is sandboxed inside Flatpak?

**Comment by nanonyme** [comment] 2019-09-26 11:11
Shouldn't be. This is the only game with this issue.

**Comment by Lyle-Tafoya** [comment] 2019-09-26 11:55
I have just discovered 2 ways to fix this on my machine.

1) Enable timer based scheduling for pulseaudio. This is enabled by default on most systems as far as I am aware. I disabled it on my machine so I could have control over fragment size and count to optimize for latency.

2) If you want to keep timer based scheduling disabled in your pulseaudio settings or if maybe you are experiencing the problem even with timer based scheduling enabled, you can go into the launch options for Crypt of the Necrodancer and set "PULSE_LATENCY_MSEC=60 %command%". It is possible you might need to adjust the value for your system.

**Comment by nanonyme** [comment] 2019-09-26 12:31
The first sounds like a proper solution to me. We should find out why it's not enabled in runtime if it's not.

**Comment by nanonyme** [comment] 2019-09-26 12:33
If this doesn't reproduce with timer-based scheduling on and it was disabled by user, I'm leaning to just closing as not a bug.

**Comment by HaasJona** [comment] 2019-09-26 12:34
As far as I'm aware, i haven't done any special pulseaudio configuration on my system. So if timer based scheduling is enabled by default on my system, and it works natively, I would assume that for some reason it's disabled inside the Flatpak runtime and that should be fixed.

**Comment by nanonyme** [comment] 2019-09-26 12:39
You can enter sandbox through flatpak run --command=bash com.valvesoftware.Steam

I don't know which setting controls this.

**Comment by Lyle-Tafoya** [comment] 2019-09-26 12:41
If it works with native Steam and timer-based scheduling disabled, it should also work with flatpak Steam and timer-based scheduling disabled. That would still be a bug in my book, as I do not consider it to be a valid solution to enable timer based scheduling. Flatpak Steam games should work with the same pulseaudio configurations as native Steam games.

**Comment by nanonyme** [comment] 2019-10-03 18:57
I suggest filing an issue on https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues since that's where the PulseAudio in the runtime comes from.

**Comment by HaasJona** [comment] 2019-10-04 06:04
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/899

**Comment by nanonyme** [comment] 2019-10-04 06:13
Than you.

**Comment by valentindavid** [comment] 2019-10-07 11:22
@Lyle-Tafoya Are you saying that Crypt of the Necrodancer works properly natively with timer-based scheduling disabled?

**Comment by nanonyme** [comment] 2022-06-12 18:47
Does this reproduce with PipeWire on host instead of PulseAudio?

**Closed** 2022-07-04 21:02 UTC
