### ISSUE TITLE
DOOM (2016) crashes on launch

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.valvesoftware.Steam#465] opened 2019-09-29 21:22 UTC
**Game information**
DOOM (2016)

**Distribution name and version where applicable**
Fedora 30 Workstation x86_64

**Flatpak info**
Flatpak 1.4.3

default
host

(Radeon RX 580)

**Problem description**
DOOM (2016) crashes right after launch with "Unhandled Exception" error window being displayed. It used to work fine ~week ago and started crashing after some recent Steam Flatpak update.

I am using latest Proton 4.11-6 and Vulkan renderer.

**Does this issue reproduce with native Steam**
Have not tested, but it should work.

**Comment by nanonyme** [comment] 2019-09-29 21:25
We got Mesa 19.2.0 some time ago. Might be related.

**Comment by AsciiWolf** [comment] 2019-09-30 18:34
Yeah, this may be the reason. I remember it using older Mesa 19.1.7 (I think) when it worked fine.

**Comment by nanonyme** [comment] 2019-09-30 19:27
Okay, please report to https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues
Does any other Vulkan game work for you?

**Comment by AsciiWolf** [comment] 2019-09-30 19:30
Yeah, I tried Kingdom Come: Deliverance and it worked fine. Maybe the issue happens only with 64-bit Wine binaries.

**Comment by nanonyme** [comment] 2019-09-30 19:31
Also reporting to https://bugzilla.freedesktop.org/ probably wouldn't hurt to get driver developer attention. You probably do need better diagnostics though.

**Comment by FastOSlinux** [comment] 2019-10-01 20:30
> **Game information**
> DOOM (2016)
> 
> **Distribution name and version where applicable**
> Fedora 30 Workstation x86_64
> 
> **Flatpak info**
> Flatpak 1.4.3
> 
> default
> host
> 
> (Radeon RX 580)
> 
> **Problem description**
> DOOM (2016) crashes right after launch with "Unhandled Exception" error window being displayed. It used to work fine ~week ago and started crashing after some recent Steam Flatpak update.
> 
> I am using latest Proton 4.11-6 and Vulkan renderer.
> 
> **Does this issue reproduce with native Steam**
> Have not tested, but it should work.

work for me

Steam on beta participation
Fedora 31 (gnome wayland)
mesa 19.2
RX 580

Game in vulkan mode (doom64vk)
2560x1080 ultra

**Comment by nanonyme** [comment] 2019-10-07 07:13
LLVM for Mesa was just updated to 9 to support Navi. Is this still failing the same way?

**Comment by doraskayo** [comment] 2019-10-08 11:31
@AsciiWolf, I recommend trying to downgrade `org.freedesktop.Platform`, `org.freedesktop.Platform.GL.default` and `com.valvesoftware.Steam` to pinpoint the commit that introduced the issue. It would greatly help in finding the root cause.

See [this link](https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading) for instructions on how to downgrade flatpaks.

**Comment by AsciiWolf** [comment] 2019-10-09 11:00
I am currently without my desktop computer, I will try it once I have my desktop PC back.

**Comment by monterrr** [comment] 2019-10-11 14:44
Since I have updated flatpaks, I think it was steam only, a few days ago there are many games that refuse to launch I am using the nvidia proprietary drivers.

**Comment by nanonyme** [comment] 2019-10-11 17:34
This app has not updated in last 7 days. If there's been a Steam update since then, it has been by Valve, not us.

**Comment by monterrr** [comment] 2019-10-11 18:11
Im having this problem for a few weeks now and I'm pretty sure this problem is from a flatpak update of steam, affected aps launch sucessfuly the first times then stops working.

**Comment by monterrr** [comment] 2019-10-11 19:24
I'm using fedora 30 workstation, this is the output of one artifex mundi native linux game, I've tested two games from them and they occur on the two that I've tested.

Cmd output:

ERROR: ld.so: object '/home/****/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 814030, ActionID 3] : LaunchApp changed task to Completed with ""
>>> Adding process 489 for game ID 814030
Critical error occured !
signal 11 (Segmentation fault), address is (nil) from (nil)
[001]: [(nil)]
Game removed: AppID 814030 "", ProcID 488 
Exiting app 814030
No cached sticky mapping in ActivateActionSet.JS method call Messaging.PostMessage with 4 arguments
JS method call Messaging.PostMessage with 4 arguments
JS method call Messaging.PostMessage with 4 arguments
JS method call Messaging.PostMessage with 4 arguments

**Comment by doraskayo** [comment] 2019-10-11 20:10
@monterrr, if you believe this was due to an update to `com.valvesoftware.Steam`, please find the commit which introduced this issue. See instructions in my previous comment.

**Comment by monterrr** [comment] 2019-10-12 11:55
Ok, this is the last commit working: c3b8f1dbb3a4f565606999629ad1fc02cda2b93ee6b95c0af7526c45a12ba760

With this commit I can run Queen's Quest 4 (although it still exits some times but runs in the next try, this I think has ever been a problem with artifex mundi games).
And I can run Chronicles of Magic: Divided Kingdoms with proton but not native, it still exits every time but I was able to previously play it to the end and finish with the native version so I don't know what's the problem.

**Comment by nanonyme** [comment] 2019-10-12 12:54
Was there some easy way to map those to git commits?

**Comment by monterrr** [comment] 2019-10-12 12:58
Maybe can find the one by the subject and date?
$ flatpak remote-info --log flathub com.valvesoftware.Steam

 Commit: c3b8f1dbb3a4f565606999629ad1fc02cda2b93ee6b95c0af7526c45a12ba760
   Subject: Use released tag of shared-library-guard (c73d3108)
      Date: 2019-10-01 17:04:52 +0000

**Comment by nanonyme** [comment] 2019-10-12 17:06
Ah. Looks like the workaround for Steam bug is breaking other games. You can use SHARED_LIBRARY_GUARD=0 to disable all workarounds.

**Comment by nanonyme** [comment] 2019-10-12 18:45
Sounds to me either

* using audit library still affects library load order
* this game will not work with SDL 2.0.10 

I'm hoping it's the latter as plan is to remove the workaround when Steam unpins their SDL.

**Comment by monterrr** [comment] 2019-10-12 18:46
I would still like to see @AsciiWolf test this commit.

**Comment by nanonyme** [comment] 2019-10-12 18:48
The commit is exactly the SDL workaround I talked about above. But sure.

**Comment by monterrr** [comment] 2019-10-12 20:02
Just saying case I don't know if it's the same bug, the dates from bug report and commit don't match.

**Comment by AsciiWolf** [comment] 2019-10-17 22:24
@nanonyme I unfortunately still don't have my desktop PC back. However, I tested it on my friend's computer with similar configuration (Intel CPU, AMD RX 590, Fedora 31) today and DOOM still crashes. However, I didn't test any older commit.

**Comment by doraskayo** [comment] 2019-10-20 10:40
@AsciiWolf, have you tested after f8688c7871c11213a1b96af2c3cbb45ee45f795a was released to `stable`?

**Comment by AsciiWolf** [comment] 2019-10-20 11:40
@doraskayo I just tested it again - still the same issue.

**Comment by doraskayo** [comment] 2019-10-20 19:31
Perhaps it's this regression in Mesa 19.2: https://gitlab.freedesktop.org/mesa/mesa/issues/1902

It was fixed in master, but hasn't been picked for the 19.2 branch yet.

**Comment by nanonyme** [comment] 2019-10-20 19:44
The change is just a drirc option. Technically that's just meant to be defaults with user overrides. https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2254/diffs

**Comment by nanonyme** [comment] 2019-10-20 19:44
https://dri.freedesktop.org/wiki/ConfigurationInfrastructure/

**Comment by nanonyme** [comment] 2019-10-20 19:49
This seems trivial to backport, created https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/906

**Comment by Zlopez** [comment] 2019-11-22 10:09
I tried it today and the Doom is now launching without issue.

**Closed** 2020-03-25 18:33 UTC
