### ISSUE TITLE
No sound in factorio

### ISSUE THREAD

**Issue by pschichtel** [flathub/com.valvesoftware.Steam#332] opened 2019-03-25 17:56 UTC
**Game information**
- Factorio

**Distribution name and version where applicable**
Archlinux Stable

**Flatpak info**
$ flatpak --version
Flatpak 1.2.3
$ flatpak --gl-drivers 
default
host

**Problem description**
Game is unable to initialize sound and disables it. The log says it can't find /dev/dsp. Setting the start options to `padsp %command%` "solves" the problem. This has definitely worked a few weeks back (still this year).

**Does this issue reproduce with native Steam**
Have not tested, but I suspect yes.

**Comment by nanonyme** [comment] 2019-03-25 18:13
Possibly duplicate of #325

**Comment by Pixelnarium** [comment] 2019-03-29 08:48
Fixed in the latest runtime update. Tested it myself. Also all my other games (Crypt of the Necrodancer, Lovers in a dangerous spacetime, ...) are fixed now but I don't have the two other games ( https://github.com/flathub/com.valvesoftware.Steam/issues/325 and https://github.com/flathub/com.valvesoftware.Steam/issues/333)

**Closed** 2019-03-29 10:30 UTC
